#!/usr/bin/env python3
"""Engångsskript: ersätt de gamla versala prefix-posterna med systematiska
streck-former och infoga hela prefix-listan i data/ordlista.json.

- Tar bort de gamla (prefix)-posterna UTOM de som saknar motsvarighet i den
  nya listan (Giga, Krikos, Mylo, Psoa lämnas orörda).
- Infogar varje ny post in-place i rätt bokstavsgrupp (casefold-ordning),
  rena tillägg utan att flytta befintliga rader.
- Assimilerade former skrivs in i original-prefixets post (ingen egen post).
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data" / "ordlista.json"

# Gamla versala prefix-poster som ska ERSÄTTAS (Giga/Krikos/Mylo/Psoa behålls).
REMOVE = {
    "Ab", "Ad", "Adeno", "Ante", "Bi", "Cephale", "Chondros", "Di", "Ecto",
    "Endo", "Epi", "Ethmos", "Exo", "Extra", "Gaster", "Glosso", "Hemi",
    "Histo", "Hyper", "Hypo", "Infra", "Inter", "Intra", "Iso", "Macro",
    "Mastos", "Meso", "Meta", "Metro", "Micro", "Mono", "Morphos", "Myelo",
    "Myo", "Odont", "Omphalo", "Onko-", "Oophor", "Para", "Peri", "Phreno",
    "Poly", "Post", "Pre", "Pro", "Pseudo", "Quadri", "Retro", "Rhino",
    "Semi", "Somato", "Spondylo", "Sub", "Super", "Supra", "Syn", "Tri", "Uni",
}


def P(term, definition):
    return {"term": term, "def": definition}


# PREFIXES fylls på nedan, ett block per bokstav.
PREFIXES = []

# === PREFIX-DATA: INFOGAS HÄR ===

PREFIXES += [
    # --- A ---
    P("a-", "Prefix: o-, icke-, utan (negation, 'alfa privativum'). (prefix) Av grek. a- = inte, utan. Före vokal blir formen an-. Ex: afebril = utan feber. Jfr an-."),
    P("ab-", "Prefix: bort från, ifrån. (prefix) Av lat. ab = från. Ex: abduktion = föra bort från kroppens medellinje. Jfr ad-."),
    P("abs-", "Prefix: bort från (form av ab- före c, t, q). (prefix) Av lat. abs = från. Ex: abstinens = avhållsamhet. Jfr ab-."),
    P("acet- / aceto-", "Prefix: ättiks-, acetyl-. (prefix) Av lat. acetum = ättika. Ex: acetonemi = aceton i blodet."),
    P("acid- / acido-", "Prefix: sur, syra-. (prefix) Av lat. acidus = sur. Ex: acidos = försurning av kroppen."),
    P("acou- / acu-", "Prefix: hörsel-. (prefix) Av grek. akouein = höra. Ex: presbyakusi = åldersbetingad hörselnedsättning."),
    P("acr- / acro-", "Prefix: spets, ytterst, höjd, extremitet. (prefix) Av grek. akron = spets, yttersta del. Ex: akromegali = förstoring av kroppens yttersta delar."),
    P("actino-", "Prefix: stråle, strålformig. (prefix) Av grek. aktis = stråle. Ex: aktinomykos = strålsvampssjukdom."),
    P("ad-", "Prefix: till, mot, intill. (prefix) Av lat. ad = till, mot. Assimileras till ac-, af-, ag-, al-, ap-, as-, at- före vissa konsonanter. Ex: adduktion = föra mot kroppens medellinje. Jfr ab-."),
    P("aden- / adeno-", "Prefix: körtel-. (prefix) Av grek. aden = körtel. Ex: adenom = godartad körteltumör."),
    P("adip- / adipo-", "Prefix: fett-. (prefix) Av lat. adeps (adipis) = fett. Ex: adipocyt = fettcell."),
    P("aer- / aero-", "Prefix: luft, gas. (prefix) Av grek. aer = luft. Ex: aerob = som kräver syre."),
    P("alge- / algesi- / algo-", "Prefix: smärta. (prefix) Av grek. algos = smärta. Ex: analgesi = smärtfrihet."),
    P("all- / allo-", "Prefix: annan, olik, avvikande. (prefix) Av grek. allos = annan. Ex: allogen = från annan individ av samma art."),
    P("ambi-", "Prefix: båda, åt båda sidor. (prefix) Av lat. ambo = båda. Ex: ambidexter = lika händig med båda händerna."),
    P("ambly-", "Prefix: trubbig, försvagad, dunkel. (prefix) Av grek. amblys = trubbig, slö. Ex: amblyopi = nedsatt synskärpa utan synlig ögonskada."),
    P("amphi- / ampho-", "Prefix: båda, runtom, dubbel. (prefix) Av grek. amphi = på båda sidor. Ex: amfiartros = led med begränsad rörlighet."),
    P("amylo-", "Prefix: stärkelse-. (prefix) Av grek. amylon = stärkelse. Ex: amyloid = stärkelseliknande inlagring."),
    P("an-", "Prefix: o-, icke-, utan (negation före vokal). (prefix) Av grek. an- = inte, utan. Ex: anemi = brist på blod; anestesi = känsellöshet. Jfr a-."),
    P("ana- (grek.)", "Prefix: upp, åter, isär, tillbaka. (prefix) Av grek. ana = upp, åter. Ex: anabolism = uppbyggande ämnesomsättning."),
    P("andro-", "Prefix: man, manlig. (prefix) Av grek. aner (andros) = man. Ex: androgen = manligt könshormon."),
    P("angi- / angio-", "Prefix: kärl-, blodkärl. (prefix) Av grek. angeion = kärl. Ex: angiografi = kärlröntgen."),
    P("aniso-", "Prefix: olik, ojämn. (prefix) Av grek. anisos = olik (a- + isos = lika). Ex: anisokori = olika stora pupiller."),
    P("ankyl- / ankylo-", "Prefix: krokig, hopväxt, stel. (prefix) Av grek. ankylos = krokig. Ex: ankylos = förbening och stelhet i en led."),
    P("ant-", "Prefix: mot, emot (form av anti- före vokal). (prefix) Av grek. anti = mot. Ex: antacida = syraneutraliserande medel. Jfr anti-."),
    P("ante-", "Prefix: framför, före, innan. (prefix) Av lat. ante = före. Ex: anteflexion = framåtböjning."),
    P("antero-", "Prefix: främre, framtill. (prefix) Av lat. anterior = främre. Ex: anterolateral = framtill och åt sidan."),
    P("anthrac- / anthraco-", "Prefix: kol, kolsvart. (prefix) Av grek. anthrax = kol. Ex: antrakos = koldammslunga."),
    P("anthropo-", "Prefix: människa. (prefix) Av grek. anthropos = människa. Ex: antropometri = mätning av människokroppen."),
    P("anti-", "Prefix: mot, emot, motverkande. (prefix) Av grek. anti = mot. Före vokal blir formen ant-. Ex: antikropp = försvarsprotein mot främmande ämnen."),
    P("antr- / antro-", "Prefix: hålrum, antrum. (prefix) Av grek. antron = grotta, hålrum. Ex: antrum = magsäckens nedre del."),
    P("apo-", "Prefix: bort, från, åtskild. (prefix) Av grek. apo = bort från. Före vokal/h blir formen ap-/aph-. Ex: apoptos = programmerad celldöd."),
    P("aqu- / aqua- / aque- / aquo-", "Prefix: vatten-. (prefix) Av lat. aqua = vatten. Ex: aqueductus = vattengång (kanal i hjärnan)."),
    P("arachn- / arachno-", "Prefix: spindel-, spindelvävsliknande. (prefix) Av grek. arachne = spindel. Ex: arachnoidea = spindelvävshinnan kring hjärnan."),
    P("arch- / arche- / archi-", "Prefix: först, ursprunglig, främst. (prefix) Av grek. arche = början, ursprung. Ex: arkenteron = urtarm hos embryot."),
    P("arteri- / arterio-", "Prefix: artär-, pulsåder. (prefix) Av grek. arteria = pulsåder. Ex: arterioskleros = åderförkalkning."),
    P("arthr- / arthro-", "Prefix: led-. (prefix) Av grek. arthron = led. Ex: artrit = ledinflammation."),
    P("atel- / atelo-", "Prefix: ofullständig, ofullbordad. (prefix) Av grek. ateles = ofullständig. Ex: atelektas = sammanfallen, luftlös lunga."),
    P("athero-", "Prefix: gröt, grötlik. (prefix) Av grek. athere = gröt. Ex: ateroskleros = åderförfettning med grötlika plack."),
    P("atmo-", "Prefix: ånga, gas. (prefix) Av grek. atmos = ånga. Ex: atmosfär = lufthölje."),
    P("atri- / atrio-", "Prefix: förmak-. (prefix) Av lat. atrium = förgård, förmak. Ex: atrioventrikulär = mellan förmak och kammare."),
    P("audi- / audio-", "Prefix: hörsel-. (prefix) Av lat. audire = höra. Ex: audiometri = hörselmätning."),
    P("aur- / auri- / auro-", "Prefix: öra-. (prefix) Av lat. auris = öra. Ex: aurikel = ytteröra/förmaksöra."),
    P("aut- / auto-", "Prefix: själv, egen. (prefix) Av grek. autos = själv. Ex: autoimmun = riktad mot den egna kroppen."),
    P("axio-", "Prefix: axel-, längsaxel. (prefix) Av grek. axon = axel. Ex: axial = som rör kroppens längsaxel."),
    P("azoto-", "Prefix: kväve-. (prefix) Av fr. azote = kväve (grek. a- + zoe = utan liv). Ex: azotemi = förhöjda kvävehaltiga slaggprodukter i blodet."),
    # --- B ---
    P("balan- / balano-", "Prefix: ollon-. (prefix) Av grek. balanos = ekollon. Ex: balanit = inflammation i ollonet."),
    P("bar- / baro-", "Prefix: tryck, tyngd. (prefix) Av grek. baros = tyngd. Ex: baroreceptor = tryckkänslig sinnescell."),
    P("bary-", "Prefix: tung, djup. (prefix) Av grek. barys = tung. Ex: baryfoni = djup, grov röst."),
    P("basi- / basio-", "Prefix: bas, grund, nedre del. (prefix) Av grek. basis = grund, fot. Ex: basion = främre kanten av stora nackhålet."),
    P("bi-", "Prefix: två, dubbel, två gånger. (prefix) Av lat. bi- = två. Ex: bilateral = dubbelsidig; biceps = tvåhövdad muskel."),
    P("bili-", "Prefix: galla-. (prefix) Av lat. bilis = galla. Ex: bilirubin = gallfärgämne."),
    P("bio-", "Prefix: liv, levande. (prefix) Av grek. bios = liv. Ex: biopsi = vävnadsprov från levande vävnad."),
    P("bis-", "Prefix: två gånger, dubbel. (prefix) Av lat. bis = två gånger. Ex: bisferisk puls = puls med två toppar. Jfr bi-."),
    P("blast- / blasto-", "Prefix: grodd, omogen cell, anlag. (prefix) Av grek. blastos = grodd, skott. Ex: blastocyst = tidigt embryostadium."),
    P("blenn- / blenno-", "Prefix: slem-. (prefix) Av grek. blenna = slem. Ex: blennorré = slemflöde."),
    P("blephar- / blepharo-", "Prefix: ögonlock-. (prefix) Av grek. blepharon = ögonlock. Ex: blefarit = ögonlocksinflammation."),
    P("brachi- / brachio-", "Prefix: arm-, överarm. (prefix) Av lat. brachium = arm. Ex: m. brachialis = överarmsmuskeln."),
    P("brady-", "Prefix: långsam. (prefix) Av grek. bradys = långsam. Ex: bradykardi = långsam hjärtrytm."),
    P("brom- / bromo-", "Prefix: stank, lukt; brom (grundämne). (prefix) Av grek. bromos = stank. Ex: bromhidros = illaluktande svett."),
    P("bronch- / bronchi- / broncho-", "Prefix: luftrör-. (prefix) Av grek. bronchos = luftrör. Ex: bronkit = luftrörskatarr."),
    P("bucc- / bucco-", "Prefix: kind-. (prefix) Av lat. bucca = kind. Ex: buckal = som vetter mot kinden."),
    P("burs- / burso-", "Prefix: slemsäck-, säck. (prefix) Av lat. bursa = säck, pung. Ex: bursit = slemsäcksinflammation."),
    # --- C ---
    P("cac- / caco-", "Prefix: dålig, sjuklig, missbildad. (prefix) Av grek. kakos = dålig. Ex: kakosmi = förnimmelse av obehaglig lukt."),
    P("calci-", "Prefix: kalk-, kalcium. (prefix) Av lat. calx (calcis) = kalk. Ex: kalcinos = kalkinlagring i vävnad."),
    P("calor- / calori-", "Prefix: värme-. (prefix) Av lat. calor = värme. Ex: kalori = värmeenhet."),
    P("capn- / capno-", "Prefix: koldioxid; rök. (prefix) Av grek. kapnos = rök. Ex: kapnografi = mätning av utandad koldioxid."),
    P("carcin- / carcino-", "Prefix: cancer-, kräfta. (prefix) Av grek. karkinos = kräfta. Ex: karcinom = elakartad tumör i epitelvävnad."),
    P("cardi- / cardio-", "Prefix: hjärta-; magmun. (prefix) Av grek. kardia = hjärta. Ex: kardiologi = läran om hjärtat."),
    P("carph- / carpho-", "Prefix: strå, skräp. (prefix) Av grek. karphos = strå. Ex: karfologi = plockande i sängkläderna vid svår sjukdom."),
    P("carpo-", "Prefix: handlov-, karpalben; frukt. (prefix) Av grek. karpos = handlov; även frukt. Ex: karpalben = handlovens ben."),
    P("caryo-", "Prefix: kärna, cellkärna. (prefix) Av grek. karyon = nöt, kärna. Ex: karyotyp = kromosomuppsättning. Jfr kary-/karyo-."),
    P("cata-", "Prefix: ned, nedåt, isär. (prefix) Av grek. kata = ned. Ex: katabolism = nedbrytande ämnesomsättning."),
    P("caud- / caudo-", "Prefix: svans-, nedåt mot svansänden. (prefix) Av lat. cauda = svans. Ex: kaudal = mot svansänden/nedre delen av kroppen."),
    P("caust- / causto-", "Prefix: brännande, frätande. (prefix) Av grek. kaustos = bränd. Ex: kaustisk = frätande."),
    P("cav- / cavi- / cavo-", "Prefix: hålighet-, hålrum. (prefix) Av lat. cavus = ihålig. Ex: vena cava = hålvenen."),
    P("cecal- / ceco-", "Prefix: blindtarm-, cekum. (prefix) Av lat. caecum = blindtarm (av caecus = blind). Ex: cekostomi = öppning till blindtarmen."),
    P("cel- / celo-", "Prefix: bråck, svulst; hålrum. (prefix) Av grek. kele = bråck, svulst (även koilos = hålig). Ex: hydrocele = vätskebråck."),
    P("centi-", "Prefix: hundra, hundradel. (prefix) Av lat. centum = hundra. Ex: centimeter = hundradels meter."),
    P("centr- / centro-", "Prefix: mittpunkt-, centrum. (prefix) Av grek. kentron = medelpunkt. Ex: centromer = kromosomens mittparti."),
    P("cephal- / cephalo-", "Prefix: huvud-. (prefix) Av grek. kephale = huvud. Ex: cefalokaudal = från huvud mot svansände."),
    P("cerat- / cerato-", "Prefix: horn-, hornhinna. (prefix) Av grek. keras (keratos) = horn. Ex: keratin = hornämne. Jfr kerat-/kerato-."),
    P("cerebr- / cerebro-", "Prefix: hjärna-, storhjärna. (prefix) Av lat. cerebrum = hjärna. Ex: cerebral = som rör hjärnan."),
    P("cervic- / cervico-", "Prefix: hals-, nacke; livmoderhals. (prefix) Av lat. cervix (cervicis) = hals. Ex: cervikal = som rör halsen/halsryggen."),
    P("cheil- / cheilo-", "Prefix: läpp-. (prefix) Av grek. cheilos = läpp. Ex: keilit = läppinflammation."),
    P("cheir- / cheiro- / chir- / chiro-", "Prefix: hand-. (prefix) Av grek. cheir = hand. Ex: kiropraktor = behandlare med handgrepp."),
    P("chem- / chemo-", "Prefix: kemi-, kemisk. (prefix) Av grek. chemeia = kemi. Ex: kemoterapi = cellgiftsbehandling."),
    P("chion- / chiono-", "Prefix: snö-. (prefix) Av grek. chion = snö. Ex: kionoblepsi = snöblindhet (äldre term)."),
    P("chlamyd- / chlamydo-", "Prefix: mantel, hölje. (prefix) Av grek. chlamys = mantel. Ex: klamydia = bakterie med höljeliknande inneslutning."),
    P("chlor- / chloro-", "Prefix: grön; klor. (prefix) Av grek. chloros = ljusgrön. Ex: kloros = bleksot (äldre anemiform)."),
    P("chol- / chole- / cholo-", "Prefix: galla-. (prefix) Av grek. chole = galla. Ex: kolecystit = gallblåseinflammation."),
    P("choledoch- / choledocho-", "Prefix: stora gallgången. (prefix) Av grek. chole = galla + dechomai = ta emot. Ex: koledokus = stora gallgången."),
    P("chondr- / chondrio- / chondro-", "Prefix: brosk-; korn. (prefix) Av grek. chondros = brosk, korn. Ex: kondrocyt = broskcell."),
    P("chord- / chordo-", "Prefix: sträng, ryggsträng, sena. (prefix) Av grek. chorde = sträng. Ex: notochord = ryggsträng hos embryot."),
    P("chori- / chorio-", "Prefix: hinna, korionhinna. (prefix) Av grek. chorion = fosterhinna. Ex: korion = yttre fosterhinnan."),
    P("chrom- / chromat- / chromato- / chromo-", "Prefix: färg-. (prefix) Av grek. chroma (chromatos) = färg. Ex: kromosom = färgbar kropp i cellkärnan."),
    P("chron- / chrono-", "Prefix: tid-. (prefix) Av grek. chronos = tid. Ex: kronisk = långvarig."),
    P("chrys- / chryso-", "Prefix: guld-, guldgul. (prefix) Av grek. chrysos = guld. Ex: krysoterapi = guldbehandling (äldre reumamedel)."),
    P("chyl- / chylo-", "Prefix: mjölksaft, fettrik lymfa. (prefix) Av grek. chylos = saft. Ex: kylotorax = lymfvätska i lungsäcken."),
    P("chym- / chymo-", "Prefix: saft, maginnehåll. (prefix) Av grek. chymos = saft. Ex: chymus = den halvflytande magsäcksvällingen."),
    P("cili- / cilio-", "Prefix: ögonfrans-, flimmerhår; strålkropp. (prefix) Av lat. cilium = ögonfrans. Ex: corpus ciliare = strålkroppen i ögat."),
    P("circum-", "Prefix: runt, omkring. (prefix) Av lat. circum = runt omkring. Ex: cirkumcision = omskärelse."),
    P("cirrh- / cirrho-", "Prefix: gulbrun; skrumpen. (prefix) Av grek. kirrhos = gulaktig. Ex: cirros = skrumplever."),
    P("cis- (lat.)", "Prefix: på samma sida om. (prefix) Av lat. cis = på denna sida. Ex: cis-läge = på samma sida."),
    P("clast- / clasto-", "Prefix: som bryter ned, krossar. (prefix) Av grek. klastos = bruten. Ex: osteoklast = bennedbrytande cell."),
    P("cleid- / cleido-", "Prefix: nyckelben-. (prefix) Av grek. kleis (kleidos) = nyckel(ben). Ex: kleidokranial = som rör nyckelben och skalle."),
    P("clin- / clino-", "Prefix: luta, böja; säng. (prefix) Av grek. klinein = luta. Ex: klinisk (av sängliggande vård)."),
    P("co-", "Prefix: med, tillsammans, gemensamt. (prefix) Av lat. con- (co- före vokal/h). Ex: koordination = samordning. Jfr con-."),
    P("coagulo-", "Prefix: koagulation-, levring. (prefix) Av lat. coagulare = få att levra sig. Ex: koagulopati = störd blodlevring."),
    P("cocc- / coccyg- / coccygo-", "Prefix: bär(formig); svansben. (prefix) Av grek. kokkos = bär, korn; kokkyx = svansben. Ex: coccyx = svansbenet."),
    P("coel- / coelo-", "Prefix: hålrum-, kroppshåla. (prefix) Av grek. koilos = ihålig. Ex: coelom = kroppshålan hos embryot."),
    P("col- / colly- / colo-", "Prefix: tjocktarm-, kolon. (prefix) Av grek. kolon = tjocktarm. Även assimilerad form av con- (med, samman) före l. Ex: kolit = tjocktarmsinflammation."),
    P("colp- / colpo-", "Prefix: slida-. (prefix) Av grek. kolpos = sköte, slida. Ex: kolposkopi = undersökning av slidan."),
    P("con-", "Prefix: med, samman, tillsammans. (prefix) Av lat. con- = med. Assimileras till co-, col-, com-, cor- före vissa konsonanter. Ex: konvergens = sammanlöpande."),
    P("contra-", "Prefix: mot, emot, motsatt. (prefix) Av lat. contra = mot. Ex: kontralateral = på motsatt sida."),
    P("copr- / copro-", "Prefix: avföring-, träck. (prefix) Av grek. kopros = träck. Ex: koprolit = intorkad, hård avföring."),
    P("cor- / core- / coreo-", "Prefix: pupill-. (prefix) Av grek. kore = pupill (egentl. flicka, docka). Även assimilerad form av con- (med) före r. Ex: korektopi = felställd pupill."),
    P("corm- / cormo-", "Prefix: stam, bål. (prefix) Av grek. kormos = trädstam. Ex: kormo- = som rör bålen."),
    P("coron- / corono-", "Prefix: krona-, kranskärl; kronutskott. (prefix) Av lat. corona = krans, krona. Ex: koronar = som rör hjärtats kranskärl."),
    P("cortic- / cortico-", "Prefix: bark-, ytterhölje (cortex). (prefix) Av lat. cortex (corticis) = bark, skal. Ex: kortikal = som rör hjärnbarken."),
    P("cost- / costo-", "Prefix: revben-. (prefix) Av lat. costa = revben. Ex: kostovertebral = mellan revben och kotpelare."),
    P("cox- / coxo-", "Prefix: höft-. (prefix) Av lat. coxa = höft. Ex: koxartros = artros i höftleden."),
    P("crani- / cranio-", "Prefix: skalle-, kranium. (prefix) Av grek. kranion = skalle. Ex: kraniotomi = öppning av skallbenet."),
    P("cren- / crenato-", "Prefix: skåra, tandad kant. (prefix) Av lat. crena = skåra. Ex: krenerad = med naggad kant."),
    P("crin- / crino-", "Prefix: avsöndra, utsöndring. (prefix) Av grek. krinein = avsöndra. Ex: endokrin = inre sekretion."),
    P("cry- / cryo-", "Prefix: köld-, kyla. (prefix) Av grek. kryos = köld. Ex: kryoterapi = köldbehandling."),
    P("crypt- / crypto-", "Prefix: dold, gömd. (prefix) Av grek. kryptos = dold. Ex: kryptorkism = icke nedvandrad testikel."),
    P("cubit- / cubito-", "Prefix: armbåge-. (prefix) Av lat. cubitus = armbåge. Ex: kubital = som rör armbågen."),
    P("culd- / culdo-", "Prefix: Douglas rum. (prefix) Av fr. cul-de-sac = återvändsgränd. Ex: kuldocentes = punktion av Douglas rum."),
    P("cut- / cuti- / cuto-", "Prefix: hud-. (prefix) Av lat. cutis = hud. Ex: subkutan = under huden."),
    P("cyan- / cyano-", "Prefix: blå, blåaktig. (prefix) Av grek. kyanos = mörkblå. Ex: cyanos = blåfärgning av huden vid syrebrist."),
    P("cycl- / cyclo-", "Prefix: cirkel, ring; strålkropp. (prefix) Av grek. kyklos = cirkel. Ex: cyklit = inflammation i ögats strålkropp."),
    P("cylindr- / cylindro-", "Prefix: cylinder-, rörformig. (prefix) Av grek. kylindros = cylinder. Ex: cylindrom = viss körteltumör."),
    P("cyst- / cysti- / cysto-", "Prefix: blåsa-, urinblåsa; vätskeblåsa. (prefix) Av grek. kystis = blåsa. Ex: cystit = urinblåseinflammation."),
    P("cyt- / cyto-", "Prefix: cell-. (prefix) Av grek. kytos = ihåligt kärl, cell. Ex: cytologi = cellära."),
]

PREFIXES += [
    # --- D ---
    P("dacry- / dacryo-", "Prefix: tår-, tårapparat. (prefix) Av grek. dakryon = tår. Ex: dakryocystit = inflammation i tårsäcken."),
    P("dactyl- / dactylo-", "Prefix: finger-, tå. (prefix) Av grek. daktylos = finger. Ex: daktylit = inflammation i finger eller tå."),
    P("de-", "Prefix: bort, av, ned, mot-. (prefix) Av lat. de = från, bort. Ex: dehydrering = uttorkning."),
    P("deca-", "Prefix: tio. (prefix) Av grek. deka = tio. Ex: dekaliter = tio liter."),
    P("deci-", "Prefix: tiondel. (prefix) Av lat. decimus = tionde. Ex: deciliter = tiondels liter."),
    P("demi-", "Prefix: halv. (prefix) Av lat. dimidius (via fr. demi) = halv. Ex: demifasett = halv ledyta på kotkropp."),
    P("dem- / demo-", "Prefix: folk, befolkning. (prefix) Av grek. demos = folk. Ex: demografi = befolkningsstatistik."),
    P("dendr- / dendro-", "Prefix: träd, trädformig. (prefix) Av grek. dendron = träd. Ex: dendrit = trädlikt utskott på nervcell."),
    P("dent- / denti- / dento-", "Prefix: tand-. (prefix) Av lat. dens (dentis) = tand. Ex: dentin = tandben."),
    P("derm- / derma- / dermat- / dermato- / dermo-", "Prefix: hud-. (prefix) Av grek. derma (dermatos) = hud. Ex: dermatit = hudinflammation."),
    P("desm- / desmo-", "Prefix: band, ligament, sena. (prefix) Av grek. desmos = band. Ex: desmosom = cellkopplingsstruktur."),
    P("dextr- / dextro-", "Prefix: höger, åt höger. (prefix) Av lat. dexter = höger. Ex: dextrokardi = hjärtat förlagt åt höger."),
    P("di-", "Prefix: två, dubbel (grek.). (prefix) Av grek. dis = två gånger. Ex: disackarid = socker av två enheter."),
    P("dia-", "Prefix: genom, igenom, isär. (prefix) Av grek. dia = genom. Ex: diafragma = genomgående skiljevägg (mellangärdet)."),
    P("diaphor- / diaphoro-", "Prefix: svett-, transpiration. (prefix) Av grek. diaphorein = svettas ut. Ex: diafores = riklig svettning."),
    P("digiti- / digito-", "Prefix: finger-, tå. (prefix) Av lat. digitus = finger, tå. Ex: digital = som rör fingrarna."),
    P("dipl- / diplo-", "Prefix: dubbel, dubblerad. (prefix) Av grek. diploos = dubbel. Ex: diplopi = dubbelseende."),
    P("dips- / dipso-", "Prefix: törst-. (prefix) Av grek. dipsa = törst. Ex: polydipsi = onormalt stor törst."),
    P("dirhin- / dirhino-", "Prefix: med två näsgångar/näsöppningar. (prefix) Av grek. dis = två + rhis (rhinos) = näsa. Ex: dirhinisk = med två näsgångar."),
    P("dis-", "Prefix: isär, bort, motsats, brist. (prefix) Av lat. dis = isär. Före f blir formen dif-. Ex: dissektion = isärdelning."),
    P("disc- / disco-", "Prefix: skiva-, disk. (prefix) Av grek. diskos = skiva. Ex: diskit = inflammation i mellankotsskiva."),
    P("dist- / disto-", "Prefix: avlägsen, längst bort från bålen. (prefix) Av lat. distare = stå isär. Ex: distal = längre från kroppens centrum."),
    P("dolich- / dolicho-", "Prefix: lång. (prefix) Av grek. dolichos = lång. Ex: dolikocefal = långskallig."),
    P("dors- / dorsi- / dorso-", "Prefix: rygg-, baktill. (prefix) Av lat. dorsum = rygg. Ex: dorsalflexion = böjning mot ryggsidan."),
    P("drom- / dromo-", "Prefix: lopp, ledning, riktning. (prefix) Av grek. dromos = lopp. Ex: dromotrop = som påverkar retledningshastigheten."),
    P("duodeno-", "Prefix: tolvfingertarm-. (prefix) Av lat. duodenum = tolv (fingrar bred). Ex: duodenit = inflammation i tolvfingertarmen."),
    P("dynam- / dynamo-", "Prefix: kraft, styrka. (prefix) Av grek. dynamis = kraft. Ex: dynamometer = mätare av muskelstyrka."),
    P("dys-", "Prefix: dålig, svår, störd, onormal. (prefix) Av grek. dys = dålig, svår. Ex: dysfagi = sväljningssvårighet."),
    # --- E ---
    P("e-", "Prefix: ut, ur, bort (form av ex- före konsonant). (prefix) Av lat. e/ex = ut. Ex: efferent = utåtledande. Jfr ex-."),
    P("ec-", "Prefix: ut, utåt, ur. (prefix) Av grek. ek = ut. Ex: ektopi = läge utanför det normala."),
    P("echin- / echino-", "Prefix: tagg-, igelkott. (prefix) Av grek. echinos = igelkott. Ex: ekinokock = blåsmask (dvärgbandmask)."),
    P("echo-", "Prefix: eko-, återkastat ljud. (prefix) Av grek. echo = ljud, eko. Ex: ekokardiografi = ultraljud av hjärtat."),
    P("ect- / ecto-", "Prefix: yttre, utanför, utåt. (prefix) Av grek. ektos = utanför. Ex: ektoderm = yttre groddbladet."),
    P("ectrop- / ectropo-", "Prefix: utåtvänd, utåtvridning. (prefix) Av grek. ektrope = vändning utåt. Ex: ektropion = utåtvänt ögonlock."),
    P("elai- / elaio-", "Prefix: olja-. (prefix) Av grek. elaion = olja. Ex: elaiom = oljegranulom."),
    P("electr- / electro-", "Prefix: elektrisk, elektricitet. (prefix) Av grek. elektron = bärnsten. Ex: elektrokardiografi (EKG)."),
    P("elytr- / elytro-", "Prefix: slida- (vagina). (prefix) Av grek. elytron = hölje, slida. Ex: elytroplastik = plastik på slidan (äldre term)."),
    P("emet- / emeto-", "Prefix: kräkning-. (prefix) Av grek. emesis = kräkning. Ex: emetikum = kräkmedel."),
    P("emia-", "Efterled: tillstånd i blodet. (prefix) Av grek. haima = blod. Ex: hyperglykemi = högt blodsocker (-emi = i blodet)."),
    P("en-", "Prefix: i, in, inuti. (prefix) Av grek. en = i. Före b, m, p blir formen em-. Ex: empyem = varansamling i en kroppshåla."),
    P("encephal- / encephalo-", "Prefix: hjärna-. (prefix) Av grek. enkephalos = hjärna (en = i + kephale = huvud). Ex: encefalit = hjärninflammation."),
    P("end- / endo-", "Prefix: inre, inuti, inåt. (prefix) Av grek. endon = inom. Ex: endokard = hjärtats innerhinna."),
    P("enter- / entero-", "Prefix: tarm-, tunntarm. (prefix) Av grek. enteron = tarm. Ex: enterit = tarminflammation."),
    P("ento-", "Prefix: inom, inre. (prefix) Av grek. entos = innanför. Ex: entoderm = inre groddbladet."),
    P("eosino-", "Prefix: rödfärgande (av eosin). (prefix) Av grek. eos = morgonrodnad. Ex: eosinofil = vit blodkropp som färgas av eosin."),
    P("ep-", "Prefix: på, ovanpå (form av epi- före vokal). (prefix) Av grek. epi = på. Ex: eponym = namn efter en person. Jfr epi-."),
    P("eph-", "Prefix: på, ovanpå (form av epi- före aspirata). (prefix) Av grek. epi = på. Ex: efelider = fräknar. Jfr epi-."),
    P("epi-", "Prefix: på, ovanpå, över, vid. (prefix) Av grek. epi = på, vid. Före vokal/h blir formen ep-/eph-. Ex: epidermis = överhud."),
    P("epididym- / epididymo-", "Prefix: bitestikel-. (prefix) Av grek. epi = på + didymos = testikel. Ex: epididymit = bitestikelinflammation."),
    P("episi- / episio-", "Prefix: blygd-, yttre könsdelar. (prefix) Av grek. epision = blygd. Ex: episiotomi = klipp i mellangården vid förlossning."),
    P("erg- / ergo-", "Prefix: arbete, verkan. (prefix) Av grek. ergon = arbete. Ex: ergometri = mätning av fysiskt arbete."),
    P("erythr- / erythro-", "Prefix: röd-. (prefix) Av grek. erythros = röd. Ex: erytrocyt = röd blodkropp."),
    P("esophag- / esophago-", "Prefix: matstrupe-. (prefix) Av grek. oisophagos = matstrupe. Ex: esofagit = matstrupsinflammation."),
    P("esthesi- / esthesio-", "Prefix: känsel-, förnimmelse. (prefix) Av grek. aisthesis = förnimmelse. Ex: anestesi = känsellöshet."),
    P("ethm- / ethmo-", "Prefix: sil-, silben. (prefix) Av grek. ethmos = sil. Ex: os ethmoidale = silbenet."),
    P("eti- / etio-", "Prefix: orsak-. (prefix) Av grek. aitia = orsak. Ex: etiologi = läran om sjukdomars orsaker."),
    P("eu-", "Prefix: god, väl, normal. (prefix) Av grek. eu = väl, god. Ex: eupné = normal andning."),
    P("eury-", "Prefix: bred, vid. (prefix) Av grek. eurys = bred. Ex: eurycefal = bredskallig."),
    P("ex-", "Prefix: ut, ur, bort. (prefix) Av lat. ex = ut. Före konsonant ofta e-, före f blir ef-. Ex: excision = bortskärande."),
    P("exo-", "Prefix: utanför, yttre, utåt. (prefix) Av grek. exo = utanför. Ex: exokrin = utsöndring till yta eller kanal."),
    P("extra-", "Prefix: utanför, bortom, utöver. (prefix) Av lat. extra = utanför. Ex: extracellulär = utanför cellen."),
    # --- F ---
    P("faci- / facio-", "Prefix: ansikte-. (prefix) Av lat. facies = ansikte. Ex: n. facialis = ansiktsnerven."),
    P("fibri- / fibro-", "Prefix: fiber-, bindväv. (prefix) Av lat. fibra = tråd, fiber. Ex: fibros = bindvävsökning."),
    P("fluor- / fluoro-", "Prefix: flöde; fluor; fluorescens. (prefix) Av lat. fluere = flyta. Ex: fluoroskopi = röntgengenomlysning i realtid."),
    P("foc- / foco-", "Prefix: härd-, brännpunkt. (prefix) Av lat. focus = härd, eldstad. Ex: fokal = härdformig, lokaliserad."),
    P("foli- / folio-", "Prefix: blad-. (prefix) Av lat. folium = blad. Ex: folsyra (av folium = blad)."),
    P("follicul- / folliculo-", "Prefix: follikel-, liten säck. (prefix) Av lat. folliculus = liten säck. Ex: follikulit = inflammation i hårsäck."),
    P("fore-", "Prefix: före, framför. (prefix) Av eng. fore = före (germanskt ursprung). Ex: forebrain = framhjärnan."),
    P("form- / formi-", "Prefix: form, gestalt; myr-. (prefix) Av lat. forma = form; formica = myra. Ex: formikation = myrkrypningar i huden."),
    P("front- / fronto-", "Prefix: panna-, pannlob; främre. (prefix) Av lat. frons (frontis) = panna. Ex: frontal = som rör pannan/framsidan."),
    P("fugi-", "Prefix: fly, driva bort. (prefix) Av lat. fugere = fly. Ex: febrifug = febernedsättande (driver bort feber)."),
    P("funct- / functi-", "Prefix: funktion-, verksamhet. (prefix) Av lat. functio = utförande. Ex: funktionell = som rör funktionen."),
    P("fung- / fungi-", "Prefix: svamp-. (prefix) Av lat. fungus = svamp. Ex: fungicid = svampdödande medel."),
    P("furc- / furco-", "Prefix: gaffel, klyka, förgrening. (prefix) Av lat. furca = gaffel. Ex: bifurkation = tudelning/förgrening."),
    # --- G ---
    P("galact- / galacto-", "Prefix: mjölk-. (prefix) Av grek. gala (galaktos) = mjölk. Ex: galaktorré = mjölkflöde."),
    P("gam- / gamo-", "Prefix: förening, parning, könscell. (prefix) Av grek. gamos = äktenskap. Ex: gamet = könscell."),
    P("gangli- / ganglio-", "Prefix: nervknut-, ganglion. (prefix) Av grek. ganglion = knöl. Ex: gangliit = inflammation i nervknut."),
    P("gastr- / gastro-", "Prefix: magsäck-, mage. (prefix) Av grek. gaster (gastros) = mage. Ex: gastrit = magkatarr."),
    P("ge- / geo-", "Prefix: jord-. (prefix) Av grek. ge = jord. Ex: geofagi = jordätande."),
    P("gel- / gelo-", "Prefix: frysa, stelna, gelé. (prefix) Av lat. gelare = frysa. Ex: gelatin = stelnat protein."),
    P("gen- / geno-", "Prefix: härkomst, alstring, anlag. (prefix) Av grek. genos = ursprung, släkte. Ex: genotyp = arvsanlag."),
    P("genu- (lat.)", "Prefix: knä-. (prefix) Av lat. genu = knä. Ex: genu valgum = kobenthet."),
    P("geri- / gero- / geront- / geronto-", "Prefix: ålderdom-, gammal. (prefix) Av grek. geron (gerontos) = gammal man. Ex: geriatrik = åldrandets medicin."),
    P("gigant- / giganto-", "Prefix: jätte-, jättestor. (prefix) Av grek. gigas (gigantos) = jätte. Ex: gigantism = jätteväxt."),
    P("gingiv- / gingivo-", "Prefix: tandkött-. (prefix) Av lat. gingiva = tandkött. Ex: gingivit = tandköttsinflammation."),
    P("glauc- / glauco-", "Prefix: gråblå, grön. (prefix) Av grek. glaukos = blågrå. Ex: glaukom = grön starr."),
    P("gli- / glio-", "Prefix: lim, stödjevävnad i nervsystemet. (prefix) Av grek. glia = lim. Ex: gliom = tumör från gliaceller."),
    P("glomerul- / glomerulo-", "Prefix: nystan-, njurnystan. (prefix) Av lat. glomerulus = litet nystan. Ex: glomerulonefrit = njurnystaninflammation."),
    P("gloss- / glosso-", "Prefix: tunga-. (prefix) Av grek. glossa = tunga. Ex: glossit = tunginflammation."),
    P("gluc- / gluco-", "Prefix: socker-, glukos; söt. (prefix) Av grek. glykys = söt. Ex: glukos = druvsocker."),
    P("glyc- / glyco-", "Prefix: söt, socker-. (prefix) Av grek. glykys = söt. Ex: glykemi = sockerhalt i blodet."),
    P("gnath- / gnatho-", "Prefix: käke-. (prefix) Av grek. gnathos = käke. Ex: prognati = framskjutande underkäke."),
    P("goni- / gonio-", "Prefix: vinkel-, hörn. (prefix) Av grek. gonia = vinkel. Ex: goniometer = vinkelmätare för leder."),
    P("granul- / granulo-", "Prefix: korn-, kornig. (prefix) Av lat. granulum = litet korn. Ex: granulocyt = kornig vit blodkropp."),
    P("graph- / grapho-", "Prefix: skriva, registrera. (prefix) Av grek. graphein = skriva. Ex: -grafi = bildregistrering."),
    P("gravi-", "Prefix: tyngd, tung; graviditet. (prefix) Av lat. gravis = tung. Ex: graviditet = havandeskap."),
    P("gyn- / gyne- / gynec- / gyneco-", "Prefix: kvinna-, kvinnlig. (prefix) Av grek. gyne (gynaikos) = kvinna. Ex: gynekologi = läran om kvinnosjukdomar."),
    P("gyr- / gyro-", "Prefix: ring, vindling, hjärnvindling. (prefix) Av grek. gyros = ring, krets. Ex: gyrus = hjärnvindling."),
]

PREFIXES += [
    # --- H ---
    P("haem- / haemat- / haemato- / haemo- / hem- / hemat- / hemato- / hemo-", "Prefix: blod-. (prefix) Av grek. haima (haimatos) = blod. Ex: hematom = blodutgjutning; hemoglobin = blodets syrebärande färgämne."),
    P("hagi- / hagio-", "Prefix: helig. (prefix) Av grek. hagios = helig. Ex: hagiologi = läran om helgon."),
    P("hal- / halo-", "Prefix: salt-; halogen. (prefix) Av grek. hals (halos) = salt. Ex: halofil = salttålig organism."),
    P("hapl- / haplo-", "Prefix: enkel, enkeluppsättning. (prefix) Av grek. haploos = enkel. Ex: haploid = med enkel kromosomuppsättning."),
    P("hect- / hecto-", "Prefix: hundra. (prefix) Av grek. hekaton = hundra. Ex: hektopascal = hundra pascal."),
    P("helc- / helco-", "Prefix: sår-. (prefix) Av grek. helkos = sår. Ex: helkos = sår (äldre term för ulcus)."),
    P("heli- / helio-", "Prefix: sol-. (prefix) Av grek. helios = sol. Ex: helioterapi = solljusbehandling."),
    P("helminth- / helmintho-", "Prefix: mask-, inälvsmask. (prefix) Av grek. helmins (helminthos) = mask. Ex: helmintiasis = maskinfektion."),
    P("hemi-", "Prefix: halv, halvsidig. (prefix) Av grek. hemi = halv. Ex: hemipares = halvsidig förlamning."),
    P("hepat- / hepato-", "Prefix: lever-. (prefix) Av grek. hepar (hepatos) = lever. Ex: hepatit = leverinflammation."),
    P("hept- / hepta-", "Prefix: sju. (prefix) Av grek. hepta = sju. Ex: heptapeptid = peptid av sju aminosyror."),
    P("herni- / hernio-", "Prefix: bråck-. (prefix) Av lat. hernia = bråck. Ex: herniering = utbuktning av vävnad genom en öppning."),
    P("heter- / hetero-", "Prefix: olik, annan, främmande. (prefix) Av grek. heteros = annan. Ex: heterogen = olikartad."),
    P("hex- / hexa-", "Prefix: sex. (prefix) Av grek. hex = sex. Ex: hexos = sockerart med sex kolatomer."),
    P("hidr- / hidro-", "Prefix: svett-. (prefix) Av grek. hidros = svett. Ex: anhidros = utebliven svettning."),
    P("hist- / histor- / histio- / histo-", "Prefix: vävnad-. (prefix) Av grek. histos = väv, vävnad. Ex: histologi = vävnadslära."),
    P("hol- / holo-", "Prefix: hel, fullständig. (prefix) Av grek. holos = hel. Ex: holokrin = sekretion där hela cellen sönderfaller."),
    P("hom- / homeo- / homo-", "Prefix: lika, samma, likformig. (prefix) Av grek. homos = samma, homoios = lik. Ex: homeostas = upprätthållande av jämvikt."),
    P("humer- / humero-", "Prefix: överarmsben-. (prefix) Av lat. humerus = överarmsben. Ex: humeral = som rör överarmsbenet."),
    P("hydr- / hydro-", "Prefix: vatten-, vätska. (prefix) Av grek. hydor = vatten. Ex: hydrocefalus = vatten i hjärnans hålrum."),
    P("hygr- / hygro-", "Prefix: fukt-, fuktig. (prefix) Av grek. hygros = fuktig. Ex: hygroskopisk = fuktupptagande."),
    P("hyl- / hylo-", "Prefix: materia, ämne, ved. (prefix) Av grek. hyle = materia. Ex: hylo- = som rör grundmateria."),
    P("hymen- / hymeno-", "Prefix: hinna-; mödomshinna. (prefix) Av grek. hymen = hinna. Ex: hymen = mödomshinnan."),
    P("hyo-", "Prefix: tungben-, U-format. (prefix) Av grek. hyoeides = U-formig. Ex: os hyoideum = tungbenet."),
    P("hyper-", "Prefix: över, för mycket, hög. (prefix) Av grek. hyper = över. Ex: hypertoni = högt blodtryck."),
    P("hypn- / hypno-", "Prefix: sömn-. (prefix) Av grek. hypnos = sömn. Ex: hypnotikum = sömnmedel."),
    P("hypo-", "Prefix: under, för lite, låg. (prefix) Av grek. hypo = under. Ex: hypotoni = lågt blodtryck."),
    P("hyps- / hypso-", "Prefix: höjd, hög. (prefix) Av grek. hypsos = höjd. Ex: hypsofobi = höjdrädsla."),
    P("hyster- / hystero-", "Prefix: livmoder-; hysteri. (prefix) Av grek. hystera = livmoder. Ex: hysterektomi = borttagande av livmodern."),
    # --- I ---
    P("iatr- / iatro-", "Prefix: läkare-, läkekonst. (prefix) Av grek. iatros = läkare. Ex: iatrogen = orsakad av medicinsk behandling."),
    P("ichthy- / ichthyo-", "Prefix: fisk-, fjällik. (prefix) Av grek. ichthys = fisk. Ex: iktyos = fiskfjällsjuka (torr, fjällande hud)."),
    P("icter- / ictero-", "Prefix: gulsot-. (prefix) Av grek. ikteros = gulsot. Ex: ikterus = gulsot."),
    P("id- / idio-", "Prefix: egen, självständig, individuell. (prefix) Av grek. idios = egen. Ex: idiopatisk = av okänd/egen orsak."),
    P("ile- / ileo-", "Prefix: krumtarm-, ileum. (prefix) Av lat. ileum = nedre tunntarmen. Ex: ileostomi = öppning från krumtarmen. Skiljs från ili-."),
    P("ili- / ilio-", "Prefix: tarmben-, höftben. (prefix) Av lat. ilium = tarmben. Ex: crista iliaca = höftbenskammen. Skiljs från ile-."),
    P("in-", "Prefix: 1) i, in, inåt; 2) icke-, o- (negation). (prefix) Av lat. in = i / in- = icke. Assimileras till il-, im-, ir- före l, m/b/p, r. Ex: injektion = införing; inkontinens = oförmåga att hålla tätt."),
    P("infra-", "Prefix: under, nedanför. (prefix) Av lat. infra = under. Ex: infraorbital = under ögonhålan."),
    P("inguin- / inguino-", "Prefix: ljumske-. (prefix) Av lat. inguen (inguinis) = ljumske. Ex: inguinal = som rör ljumsken."),
    P("ini- / inio-", "Prefix: nacke-, nackbenets utskott. (prefix) Av grek. inion = nacke. Ex: inion = nackbenets utskjutande punkt."),
    P("ino-", "Prefix: fiber-, tråd, muskel. (prefix) Av grek. is (inos) = fiber, sena. Ex: inotrop = som påverkar muskelkraften."),
    P("insul- / insulo-", "Prefix: ö-, cellö. (prefix) Av lat. insula = ö. Ex: insulin (av Langerhans cellöar)."),
    P("inter-", "Prefix: mellan, inbördes. (prefix) Av lat. inter = mellan. Ex: interkostal = mellan revbenen."),
    P("intra-", "Prefix: inom, inuti. (prefix) Av lat. intra = inom. Ex: intravenös = inuti en ven."),
    P("intro-", "Prefix: inåt, in i. (prefix) Av lat. intro = inåt. Ex: introvert = inåtvänd."),
    P("iod- / iodo-", "Prefix: jod-. (prefix) Av grek. iodes = violett (jodångans färg). Ex: jodid = jodförening."),
    P("ipsi-", "Prefix: samma, på samma sida. (prefix) Av lat. ipse = själv, samma. Ex: ipsilateral = på samma sida."),
    P("irid- / irido-", "Prefix: regnbågshinna-, iris. (prefix) Av grek. iris (iridos) = regnbåge. Ex: iridektomi = borttagande av del av regnbågshinnan."),
    P("isch- / ischo-", "Prefix: hämma, hålla tillbaka, minska. (prefix) Av grek. ischein = hålla tillbaka. Ex: ischemi = nedsatt blodflöde."),
    P("ischi- / ischio-", "Prefix: sittben-. (prefix) Av grek. ischion = höft, sittben. Ex: m. ischiocavernosus."),
    P("iso-", "Prefix: lika, samma, jämn. (prefix) Av grek. isos = lika. Ex: isoton = med samma osmotiska tryck."),
    P("isthmo-", "Prefix: smal förbindelse, näs. (prefix) Av grek. isthmos = smalt landband. Ex: isthmus = smal förbindelsedel (t.ex. i sköldkörteln)."),
    # --- J ---
    P("jejuno-", "Prefix: tomtarm-, jejunum. (prefix) Av lat. jejunus = fastande, tom. Ex: jejunit = inflammation i tomtarmen."),
    P("juxta-", "Prefix: bredvid, intill, nära. (prefix) Av lat. juxta = bredvid. Ex: juxtaglomerulär = belägen intill njurnystanet."),
    # --- K ---
    P("kary- / karyo-", "Prefix: kärna, cellkärna. (prefix) Av grek. karyon = kärna. Ex: karyolys = upplösning av cellkärnan."),
    P("kerat- / kerato-", "Prefix: horn-, hornhinna. (prefix) Av grek. keras (keratos) = horn. Ex: keratit = hornhinneinflammation."),
    P("kilo-", "Prefix: tusen. (prefix) Av grek. chilioi = tusen. Ex: kilogram = tusen gram."),
    P("kin- / kine- / kines- / kinesi- / kinesio- / kineto- / kino-", "Prefix: rörelse-. (prefix) Av grek. kinesis = rörelse. Ex: kinesiologi = läran om kroppsrörelser."),
    P("klept- / klepto-", "Prefix: stjäla-. (prefix) Av grek. kleptein = stjäla. Ex: kleptomani = tvångsmässig stöldlust."),
    P("koil- / koilo-", "Prefix: hålig, urgröpt. (prefix) Av grek. koilos = ihålig. Ex: koilonyki = skednaglar (urholkade naglar)."),
    P("kym- / kymo-", "Prefix: våg-, vågrörelse. (prefix) Av grek. kyma = våg. Ex: kymografi = registrering av vågformiga rörelser."),
    P("kyph- / kypho-", "Prefix: krökt rygg, kutryggig. (prefix) Av grek. kyphos = krokig. Ex: kyfos = utåtbuktande krökning av ryggraden."),
    # --- L ---
    P("labi- / labio-", "Prefix: läpp-. (prefix) Av lat. labium = läpp. Ex: labial = som rör läpparna."),
    P("lact- / lacti- / lacto-", "Prefix: mjölk-. (prefix) Av lat. lac (lactis) = mjölk. Ex: laktation = mjölkproduktion."),
    P("lal- / lalo-", "Prefix: tal-, talförmåga. (prefix) Av grek. lalein = tala. Ex: ekolali = upprepning av andras ord."),
    P("lapar- / laparo-", "Prefix: buk-, bukvägg. (prefix) Av grek. lapara = mjukdel, flank. Ex: laparoskopi = titthålskirurgi i buken."),
    P("laryng- / laryngo-", "Prefix: struphuvud-. (prefix) Av grek. larynx (laryngos) = struphuvud. Ex: laryngit = inflammation i struphuvudet."),
    P("later- / latero-", "Prefix: sida-, åt sidan. (prefix) Av lat. latus (lateris) = sida. Ex: lateral = mot kroppens sida."),
    P("leci- / lecido-", "Prefix: äggula; lecitin. (prefix) Av grek. lekithos = äggula. Ex: lecitin = fosfolipid utvunnet ur äggula."),
    P("lei- / leio-", "Prefix: slät, jämn. (prefix) Av grek. leios = slät. Ex: leiomyom = godartad tumör av glatt muskulatur."),
    P("lent- / lenti- / lento-", "Prefix: lins-, linsformig. (prefix) Av lat. lens (lentis) = lins. Ex: lentikulär = linsformig."),
    P("lepid- / lepido-", "Prefix: fjäll-, flagor. (prefix) Av grek. lepis (lepidos) = fjäll. Ex: lepidos = fjällning av huden."),
    P("lepr- / lepro-", "Prefix: spetälska-. (prefix) Av grek. lepra = spetälska. Ex: lepra = spetälska."),
    P("lept- / lepto-", "Prefix: tunn, smal, fin, ömtålig. (prefix) Av grek. leptos = tunn. Ex: leptomeninx = de mjuka, tunna hjärnhinnorna."),
    P("leuc- / leuco- / leuk- / leuko-", "Prefix: vit-. (prefix) Av grek. leukos = vit. Ex: leukocyt = vit blodkropp."),
    P("levo-", "Prefix: vänster, åt vänster. (prefix) Av lat. laevus = vänster. Ex: levokardi = hjärtat förlagt åt vänster."),
    P("lien- / lieno-", "Prefix: mjälte-. (prefix) Av lat. lien = mjälte. Ex: lienal = som rör mjälten."),
    P("ligat- / ligato-", "Prefix: bindning, knytning. (prefix) Av lat. ligare = binda. Ex: ligatur = avsnörande ligering av kärl."),
    P("lim- / limo-", "Prefix: hunger-. (prefix) Av grek. limos = hunger. Ex: limoterapi = svältkur (äldre term)."),
    P("lingu- / linguo-", "Prefix: tunga-. (prefix) Av lat. lingua = tunga. Ex: lingual = som rör tungan."),
    P("lip- / lipo-", "Prefix: fett-. (prefix) Av grek. lipos = fett. Ex: lipom = godartad fettknöl."),
    P("lith- / litho-", "Prefix: sten-, konkrement. (prefix) Av grek. lithos = sten. Ex: litotripsi = krossning av sten (t.ex. njursten)."),
    P("lob- / lobi- / lobo-", "Prefix: lob-, flik. (prefix) Av grek. lobos = lob, flik. Ex: lobektomi = borttagande av en lunglob."),
    P("log- / logo-", "Prefix: ord, tal; läran om. (prefix) Av grek. logos = ord, lära. Ex: logopedi = behandling av tal- och språkstörningar."),
    P("loph- / lopho-", "Prefix: kam, ås, tofs. (prefix) Av grek. lophos = kam, tofs. Ex: lofotrik = bakterie med hårtofs i ena änden."),
    P("lord- / lordo-", "Prefix: framåtkrökt rygg, svank. (prefix) Av grek. lordos = framåtböjd. Ex: lordos = inåtbuktande svank i ländryggen."),
    P("lox- / loxo-", "Prefix: sned, snedställd. (prefix) Av grek. loxos = sned. Ex: loxotomi = snitt på sned (äldre term)."),
    P("lumb- / lumbo-", "Prefix: länd-, ländrygg. (prefix) Av lat. lumbus = länd. Ex: lumbago = ryggskott."),
    P("lute- / luteo-", "Prefix: gul-, gulkropp. (prefix) Av lat. luteus = gul. Ex: corpus luteum = gulkroppen i äggstocken."),
    P("lymph- / lympha- / lymphat- / lymphato- / lympho-", "Prefix: lymf-, lymfkärl/vävnad. (prefix) Av lat. lympha = klart vatten. Ex: lymfödem = svullnad av lymfstockning."),
    P("lys- / lyso-", "Prefix: upplösning, sönderdelning. (prefix) Av grek. lysis = lösning. Ex: hemolys = upplösning av röda blodkroppar."),
    # --- M ---
    P("macr- / macro-", "Prefix: stor, lång. (prefix) Av grek. makros = stor. Ex: makrocyt = onormalt stor röd blodkropp."),
    P("mal-", "Prefix: dålig, sjuklig, fel-. (prefix) Av lat. malus = dålig. Ex: malformation = missbildning."),
    P("malac- / malaco-", "Prefix: mjuk, uppmjukning. (prefix) Av grek. malakos = mjuk. Ex: osteomalaci = benuppmjukning."),
    P("mamm- / mammi- / mammo-", "Prefix: bröst-, bröstkörtel. (prefix) Av lat. mamma = bröst. Ex: mammografi = röntgen av bröstet."),
    P("man- / mano-", "Prefix: tunn, gles; tryck. (prefix) Av grek. manos = tunn, gles. Ex: manometer = tryckmätare."),
    P("mast- / masto-", "Prefix: bröst-, bröstkörtel; vårtutskott. (prefix) Av grek. mastos = bröst. Ex: mastit = bröstkörtelinflammation."),
    P("medi- / medio-", "Prefix: mitt-, mellan. (prefix) Av lat. medius = mitten. Ex: medial = mot kroppens medellinje."),
    P("meg- / mega- / megal- / megalo-", "Prefix: stor, förstorad; miljon. (prefix) Av grek. megas (megalou) = stor. Ex: megakolon = onormalt vidgad tjocktarm."),
    P("mel- / melo-", "Prefix: lem, extremitet; kind. (prefix) Av grek. melos = lem. Ex: melalgi = smärta i en extremitet."),
    P("melan- / melano-", "Prefix: svart, mörk-. (prefix) Av grek. melas (melanos) = svart. Ex: melanin = mörkt hudpigment."),
    P("men- / meno-", "Prefix: månad-, menstruation. (prefix) Av grek. men = månad. Ex: menopaus = upphörd menstruation."),
    P("mening- / meningo-", "Prefix: hjärnhinna-, ryggmärgshinna. (prefix) Av grek. meninx (meningos) = hinna. Ex: meningit = hjärnhinneinflammation."),
    P("mer- / mero-", "Prefix: del-, segment. (prefix) Av grek. meros = del. Ex: merokrin = sekretion utan cellförlust."),
    P("mes- / meso-", "Prefix: mitt-, mellan-, mellanliggande. (prefix) Av grek. mesos = mitten. Ex: mesoderm = mellersta groddbladet."),
    P("met- / meta-", "Prefix: efter, bortom, förändring, omvandling. (prefix) Av grek. meta = efter, bortom. Ex: metabolism = ämnesomsättning; metastas."),
    P("metr- / metra- / metro-", "Prefix: 1) livmoder-; 2) mått, mätning. (prefix) Av grek. metra = livmoder; metron = mått. Ex: endometrium = livmoderslemhinnan; -metri = mätning."),
    P("micr- / micro-", "Prefix: liten, mikro-; miljondel. (prefix) Av grek. mikros = liten. Ex: mikrocefali = onormalt litet huvud."),
    P("milli-", "Prefix: tusen; tusendel. (prefix) Av lat. mille = tusen. Ex: milliliter = tusendels liter."),
    P("mio-", "Prefix: mindre, minskning. (prefix) Av grek. meion = mindre. Ex: mios = sammandragen pupill."),
    P("mis-", "Prefix: hat, motvilja; fel. (prefix) Av grek. misein = hata. Ex: misogyni = kvinnohat."),
    P("mit- / mito-", "Prefix: tråd-, trådformig. (prefix) Av grek. mitos = tråd. Ex: mitos = celldelning med trådformiga kromosomer."),
    P("mne- / mneo-", "Prefix: minne-. (prefix) Av grek. mneme = minne. Ex: amnesi = minnesförlust."),
    P("mon- / mono-", "Prefix: en, ensam, enkel. (prefix) Av grek. monos = ensam. Ex: monocyt = vit blodkropp med en kärna."),
    P("morph- / morpho-", "Prefix: form, gestalt. (prefix) Av grek. morphe = form. Ex: morfologi = läran om formen."),
    P("muc- / muci- / muco-", "Prefix: slem-, slemhinna. (prefix) Av lat. mucus = slem. Ex: mukosa = slemhinna."),
    P("multi-", "Prefix: många, flera, mång-. (prefix) Av lat. multus = mycket. Ex: multipel = mångfaldig."),
    P("my- / myo-", "Prefix: muskel-. (prefix) Av grek. mys (myos) = muskel. Ex: myokard = hjärtmuskeln."),
    P("myc- / mycet- / myceto- / myco-", "Prefix: svamp-. (prefix) Av grek. mykes (myketos) = svamp. Ex: mykos = svampinfektion."),
    P("myel- / myelo-", "Prefix: märg-, benmärg; ryggmärg. (prefix) Av grek. myelos = märg. Ex: myelit = ryggmärgsinflammation."),
    P("myring- / myringo-", "Prefix: trumhinna-. (prefix) Av lat. myringa = trumhinna. Ex: myringotomi = snitt i trumhinnan."),
    P("myx- / myxo-", "Prefix: slem-, slemartad. (prefix) Av grek. myxa = slem. Ex: myxom = slemliknande godartad tumör."),
]

PREFIXES += [
    # --- N ---
    P("nan- / nano-", "Prefix: dvärg-, mycket liten; miljarddel. (prefix) Av grek. nanos = dvärg. Ex: nanism = dvärgväxt."),
    P("narc- / narco-", "Prefix: domning, sömn, bedövning. (prefix) Av grek. narke = domning. Ex: narkos = sövning."),
    P("nas- / naso-", "Prefix: näsa-. (prefix) Av lat. nasus = näsa. Ex: nasogastrisk sond = sond via näsan till magsäcken."),
    P("nat- / nato-", "Prefix: födelse-, född. (prefix) Av lat. natus = född. Ex: neonatal = som rör nyfödda."),
    P("ne- / neo-", "Prefix: ny, nybildad. (prefix) Av grek. neos = ny. Ex: neoplasi = nybildning av vävnad (tumör)."),
    P("necr- / necro-", "Prefix: död, dödlig, vävnadsdöd. (prefix) Av grek. nekros = död. Ex: nekros = vävnadsdöd."),
    P("nemat- / nemato-", "Prefix: tråd-; rundmask. (prefix) Av grek. nema (nematos) = tråd. Ex: nematod = rundmask."),
    P("nephr- / nephro-", "Prefix: njure-. (prefix) Av grek. nephros = njure. Ex: nefrit = njurinflammation."),
    P("neur- / neuro-", "Prefix: nerv-, nervsystem. (prefix) Av grek. neuron = nerv, sena. Ex: neurologi = läran om nervsystemet."),
    P("neutr- / neutro-", "Prefix: neutral, varken eller. (prefix) Av lat. neuter = ingendera. Ex: neutrofil = vit blodkropp som färgas av neutrala färgämnen."),
    P("nevi- / nevo-", "Prefix: födelsemärke-, nevus. (prefix) Av lat. naevus = födelsemärke. Ex: nevus = pigmenterat födelsemärke."),
    P("nid- / nido-", "Prefix: bo, rede, fäste. (prefix) Av lat. nidus = bo. Ex: nidation = äggets inbäddning i livmoderslemhinnan."),
    P("no- / noo-", "Prefix: förstånd, tanke, sinne. (prefix) Av grek. nous = förstånd. Ex: noopsykisk = som rör intellektuella funktioner."),
    P("noci-", "Prefix: skada, smärta. (prefix) Av lat. nocere = skada. Ex: nociceptor = smärtkännande receptor."),
    P("nod- / nodo-", "Prefix: knöl, knuta. (prefix) Av lat. nodus = knut. Ex: nodulär = knölformig."),
    P("nom- / nomo-", "Prefix: lag, regel; fördelning. (prefix) Av grek. nomos = lag. Ex: autonom = självstyrande."),
    P("non- / nona-", "Prefix: icke; nio. (prefix) Av lat. non = icke / nonus = nionde. Ex: noninvasiv = icke ingreppskrävande."),
    P("norm- / normo-", "Prefix: normal, regelrätt. (prefix) Av lat. norma = rättesnöre. Ex: normocyt = normalstor röd blodkropp."),
    P("nos- / noso-", "Prefix: sjukdom-. (prefix) Av grek. nosos = sjukdom. Ex: nosokomial = sjukhusförvärvad."),
    P("not- / noto-", "Prefix: rygg-. (prefix) Av grek. noton = rygg. Ex: notokord = ryggsträng hos embryot."),
    P("nucle- / nucleo-", "Prefix: kärna-, cellkärna. (prefix) Av lat. nucleus = kärna. Ex: nukleotid = byggsten i DNA/RNA."),
    P("nulli-", "Prefix: ingen, noll. (prefix) Av lat. nullus = ingen. Ex: nullipara = kvinna som inte fött barn."),
    P("nyct- / nycto-", "Prefix: natt-. (prefix) Av grek. nyx (nyktos) = natt. Ex: nykturi = nattliga vattenkastningar."),
    # --- O ---
    P("ob-", "Prefix: mot, emot, framför, till. (prefix) Av lat. ob = mot. Assimileras till oc-, of-, op- före c, f, p. Ex: obstruktion = tilltäppning."),
    P("occipit- / occipito-", "Prefix: nackben-, bakhuvud. (prefix) Av lat. occiput (occipitis) = bakhuvud. Ex: occipital = som rör nackbenet."),
    P("oct- / octa- / octo-", "Prefix: åtta. (prefix) Av grek./lat. okto = åtta. Ex: oktaploid = med åttafaldig kromosomuppsättning."),
    P("ocul- / oculo-", "Prefix: öga-. (prefix) Av lat. oculus = öga. Ex: okulär = som rör ögat."),
    P("odont- / odonto-", "Prefix: tand-. (prefix) Av grek. odous (odontos) = tand. Ex: odontologi = tandläkekonst."),
    P("odyn- / odyno-", "Prefix: smärta-. (prefix) Av grek. odyne = smärta. Ex: odynofagi = smärtsam sväljning."),
    P("ogdo-", "Prefix: åttonde, åtta. (prefix) Av grek. ogdoos = åttonde. Ex: ogdo- = åttonde (sällsynt)."),
    P("ole- / oleo-", "Prefix: olja-. (prefix) Av lat. oleum = olja. Ex: oleom = oljegranulom."),
    P("olfact- / olfacto-", "Prefix: lukt-, luktsinne. (prefix) Av lat. olfacere = lukta. Ex: olfaktorisk = som rör luktsinnet."),
    P("olig- / oligo-", "Prefix: få, ringa, brist. (prefix) Av grek. oligos = få. Ex: oliguri = minskad urinmängd."),
    P("om- / omo-", "Prefix: skuldra-, axel. (prefix) Av grek. omos = skuldra. Ex: m. omohyoideus = skulderblads-tungbensmuskeln."),
    P("omphal- / omphalo-", "Prefix: navel-. (prefix) Av grek. omphalos = navel. Ex: omfalit = navelinflammation."),
    P("onc- / onco-", "Prefix: tumör, svullnad, massa. (prefix) Av grek. onkos = massa, svulst. Ex: onkologi = läran om tumörsjukdomar."),
    P("oneir- / oneiro-", "Prefix: dröm-. (prefix) Av grek. oneiros = dröm. Ex: oneiroid = drömliknande förvirringstillstånd."),
    P("onych- / onycho-", "Prefix: nagel-. (prefix) Av grek. onyx (onychos) = nagel. Ex: onykomykos = nagelsvamp."),
    P("oo-", "Prefix: ägg-, äggcell. (prefix) Av grek. oon = ägg. Ex: oocyt = äggcell."),
    P("oophor- / oophoro-", "Prefix: äggstock-. (prefix) Av grek. oophoron = äggstock. Ex: ooforit = äggstocksinflammation."),
    P("op- / opo-", "Prefix: saft, växtsaft. (prefix) Av grek. opos = saft. Även assimilerad form av ob- (mot) före p. Ex: opoterapi = organsaftbehandling (äldre term)."),
    P("ophthalm- / ophthalmo-", "Prefix: öga-. (prefix) Av grek. ophthalmos = öga. Ex: oftalmologi = läran om ögats sjukdomar."),
    P("opisth- / opistho-", "Prefix: bakåt, baktill. (prefix) Av grek. opisthen = bakom. Ex: opistotonus = bakåtböjning av kroppen i kramp."),
    P("or- / oro-", "Prefix: mun-. (prefix) Av lat. os (oris) = mun. Ex: oral = som rör munnen."),
    P("orch- / orchi- / orchid- / orchido- / orcho-", "Prefix: testikel-. (prefix) Av grek. orchis = testikel. Ex: orkit = testikelinflammation."),
    P("orex- / orexo-", "Prefix: aptit-. (prefix) Av grek. orexis = aptit. Ex: anorexi = aptitlöshet."),
    P("orth- / ortho-", "Prefix: rak, rät, normal, riktig. (prefix) Av grek. orthos = rak. Ex: ortopedi = läran om rörelseorganens sjukdomar."),
    P("os- / osmo-", "Prefix: 1) lukt; 2) tryck (osmos). (prefix) Av grek. osme = lukt; osmos = stöt. Ex: anosmi = avsaknad av luktsinne; osmos = vattenvandring genom membran."),
    P("osche- / oscheo-", "Prefix: pung-, scrotum. (prefix) Av grek. oscheon = pung. Ex: oscheocele = pungbråck."),
    P("osphresi- / osphresio-", "Prefix: lukt-, luktsinne. (prefix) Av grek. osphresis = lukt. Ex: osfresi = luktsinne."),
    P("oss- / ossi-", "Prefix: ben-, benvävnad. (prefix) Av lat. os (ossis) = ben. Ex: ossifikation = benbildning."),
    P("oste- / osteo-", "Prefix: ben-, benvävnad. (prefix) Av grek. osteon = ben. Ex: osteoporos = benskörhet."),
    P("ot- / oto-", "Prefix: öra-. (prefix) Av grek. ous (otos) = öra. Ex: otit = öroninflammation."),
    P("ov- / ovi- / ovo-", "Prefix: ägg-. (prefix) Av lat. ovum = ägg. Ex: ovulation = ägglossning."),
    P("oxal- / oxalo-", "Prefix: oxalsyra-. (prefix) Av grek. oxalis = surklöver. Ex: oxalat = salt av oxalsyra (njurstenskomponent)."),
    P("oxy-", "Prefix: 1) syre; 2) skarp, sur, spetsig. (prefix) Av grek. oxys = skarp, sur. Ex: hypoxi = syrebrist; oxycefali = spetsskalle."),
    # --- P ---
    P("pachy-", "Prefix: tjock, förtjockad. (prefix) Av grek. pachys = tjock. Ex: pakymeningit = inflammation i den hårda hjärnhinnan."),
    P("palat- / palato-", "Prefix: gom-. (prefix) Av lat. palatum = gom. Ex: palatoschis = gomspalt."),
    P("pale- / paleo-", "Prefix: gammal, urgammal. (prefix) Av grek. palaios = gammal. Ex: paleocortex = den fylogenetiskt äldsta hjärnbarken."),
    P("pan- / pant- / panto-", "Prefix: all, hel, allmän. (prefix) Av grek. pan (pantos) = allt. Ex: pandemi = epidemi över hela världen."),
    P("papul- / papulo-", "Prefix: liten knottra, papel. (prefix) Av lat. papula = liten upphöjning. Ex: papulös = med små hudknottror."),
    P("par- / para-", "Prefix: bredvid, vid sidan av, omkring; avvikande. (prefix) Av grek. para = bredvid. Ex: parestesi = avvikande känselförnimmelse."),
    P("parati- / paratio-", "Prefix: bredvid (parathyreoidea). (prefix) Av grek. para = bredvid (+ thyreoidea). Ex: paratyreoidea = bisköldkörteln. [källflagga: ovanlig kombineringsform, verifiera]"),
    P("pariet- / parieto-", "Prefix: vägg-; hjässben. (prefix) Av lat. paries (parietis) = vägg. Ex: parietal = som rör en vägg/hjässbenet."),
    P("patell- / patello-", "Prefix: knäskål-. (prefix) Av lat. patella = liten skål, knäskål. Ex: patellar = som rör knäskålen."),
    P("path- / patho-", "Prefix: sjukdom, lidande. (prefix) Av grek. pathos = lidande. Ex: patologi = läran om sjukliga förändringar."),
    P("ped- / pedi- / pedo-", "Prefix: 1) fot (lat.); 2) barn (grek.). (prefix) Av lat. pes (pedis) = fot; grek. pais (paidos) = barn. Ex: pedal = fottrampa; pediatrik = barnmedicin."),
    P("pelv- / pelvi- / pelvo-", "Prefix: bäcken-; njurbäcken. (prefix) Av lat. pelvis = bäcken, skål. Ex: pelvimetri = mätning av bäckenets mått."),
    P("pemi- / pemp-", "Prefix: blåsa, vätskeblåsa. (prefix) Av grek. pemphix = blåsa, pust. Ex: pemfigus = blåsbildande hudsjukdom. [källflagga: ovanliga former, verifiera]"),
    P("pen- / peno-", "Prefix: brist, fattigdom. (prefix) Av grek. penia = brist. Ex: cytopeni = brist på blodceller."),
    P("pene-", "Prefix: nästan, knappt. (prefix) Av lat. paene = nästan. Ex: penumbra = halvskugga (nästan skugga)."),
    P("peni-", "Prefix: penis-, manslem. (prefix) Av lat. penis = svans, manslem. Ex: penil = som rör penis."),
    P("penta-", "Prefix: fem. (prefix) Av grek. pente = fem. Ex: pentos = sockerart med fem kolatomer."),
    P("pept- / pepto-", "Prefix: matsmältning, nedbrytning. (prefix) Av grek. peptein = smälta mat. Ex: peptid = kedja av aminosyror."),
    P("per-", "Prefix: genom, igenom; mycket, helt. (prefix) Av lat. per = genom. Ex: perkutan = genom huden."),
    P("peri-", "Prefix: omkring, runt. (prefix) Av grek. peri = omkring. Ex: perikard = hjärtsäcken runt hjärtat."),
    P("perine- / perineo-", "Prefix: mellangård-, bäckenbotten. (prefix) Av grek. perineon = mellangård. Ex: perineal = som rör mellangården."),
    P("peritone- / peritoneo-", "Prefix: bukhinna-. (prefix) Av grek. peritonaion = bukhinna. Ex: peritonit = bukhinneinflammation."),
    P("peron- / peroneo-", "Prefix: vadben-, fibula. (prefix) Av grek. perone = spänne, vadben. Ex: peroneal = som rör vadbenssidan."),
    P("pess- / pesso-", "Prefix: pessar, ringformig propp. (prefix) Av grek. pessos = oval sten. Ex: pessar = ring som stöttar livmodern."),
    P("petr- / petro-", "Prefix: sten-; klippben. (prefix) Av grek. petra = klippa, sten. Ex: pars petrosa = tinningbenets klippdel."),
    P("pex- / pexo-", "Prefix: fixering, fastsättning. (prefix) Av grek. pexis = fastsättning. Ex: nefropexi = fixering av en njure i rätt läge."),
    P("phac- / phaco- / phak- / phako-", "Prefix: lins-, ögats lins. (prefix) Av grek. phakos = lins. Ex: fakoemulsifikation = upplösning av grumlad ögonlins."),
    P("phag- / phago-", "Prefix: äta, uppsluka. (prefix) Av grek. phagein = äta. Ex: fagocytos = cellers uppslukande av partiklar."),
    P("phall- / phallo-", "Prefix: penis-. (prefix) Av grek. phallos = manslem. Ex: fallisk = som rör penis."),
    P("pharmac- / pharmaco-", "Prefix: läkemedel-, gift. (prefix) Av grek. pharmakon = läkemedel. Ex: farmakologi = läran om läkemedel."),
    P("pharyng- / pharyngo-", "Prefix: svalg-. (prefix) Av grek. pharynx (pharyngos) = svalg. Ex: faryngit = svalginflammation."),
    P("phem- / phemo-", "Prefix: tal-, röst. (prefix) Av grek. pheme = tal, röst. Ex: afemi = oförmåga att tala (äldre term)."),
    P("phen- / pheno-", "Prefix: synlig, framträdande; lysa. (prefix) Av grek. phainein = visa. Ex: fenotyp = de synliga egenskaperna."),
    P("phil- / philo-", "Prefix: kärlek, dragning, benägenhet. (prefix) Av grek. philein = älska. Ex: hemofili = blödarsjuka (benägenhet att blöda)."),
    P("phleb- / phlebo-", "Prefix: ven-, blodåder. (prefix) Av grek. phleps (phlebos) = ven. Ex: flebit = veninflammation."),
    P("phob- / phobo-", "Prefix: rädsla, fruktan, motvilja. (prefix) Av grek. phobos = fruktan. Ex: fotofobi = ljuskänslighet."),
    P("phon- / phono-", "Prefix: ljud, röst. (prefix) Av grek. phone = ljud, röst. Ex: afoni = röstförlust."),
    P("phor- / phoro-", "Prefix: bära, föra; tendens. (prefix) Av grek. pherein = bära. Ex: heterofori = latent skelning (benägenhet)."),
    P("phosphat- / phosphato- / phospho-", "Prefix: fosfat-, fosfor. (prefix) Av grek. phosphoros = ljusbärare. Ex: fosfatas = fosfatklyvande enzym."),
    P("phot- / photo-", "Prefix: ljus-. (prefix) Av grek. phos (photos) = ljus. Ex: fotofobi = ljuskänslighet."),
    P("phren- / phreni- / phrenico- / phreno-", "Prefix: 1) mellangärde; 2) sinne, mentalitet. (prefix) Av grek. phren = mellangärde, sinne. Ex: n. phrenicus = mellangärdesnerven; schizofreni."),
    P("phthisi- / phthisio-", "Prefix: tärande, tvinsot (tuberkulos). (prefix) Av grek. phthisis = förtvining. Ex: ftis = lungtuberkulos (äldre term)."),
    P("phyl- / phylo-", "Prefix: stam, släkte, ras. (prefix) Av grek. phylon = stam. Ex: fylogenes = arternas utvecklingshistoria."),
    P("phylac- / phylacto-", "Prefix: skydd, försvar. (prefix) Av grek. phylax = väktare. Ex: profylax = förebyggande åtgärd."),
    P("phys- / physo-", "Prefix: luft, gas; blåsa. (prefix) Av grek. physa = luft, blåsa. Ex: fysometra = gasansamling i livmodern."),
    P("physi- / physio-", "Prefix: natur, kropp, naturlig funktion. (prefix) Av grek. physis = natur. Ex: fysiologi = läran om kroppens funktioner."),
    P("phyt- / phyto-", "Prefix: växt-. (prefix) Av grek. phyton = växt. Ex: fytoterapi = växtbaserad behandling."),
    P("picro-", "Prefix: bitter. (prefix) Av grek. pikros = bitter. Ex: pikrinsyra = bittersmakande syra."),
    P("pili- / pilo-", "Prefix: hår-. (prefix) Av lat. pilus = hår. Ex: pilomotorisk = som reser hårstrå (gåshud)."),
    P("pimel- / pimelo-", "Prefix: fett-. (prefix) Av grek. pimele = fett. Ex: pimelos = fettansamling (äldre term)."),
    P("pineal- / pinealo-", "Prefix: tallkottkörtel-. (prefix) Av lat. pinea = pinjekotte. Ex: pinealom = tumör i tallkottkörteln."),
    P("pituit- / pituito-", "Prefix: hypofys-; slem. (prefix) Av lat. pituita = slem. Ex: glandula pituitaria = hypofysen."),
    P("plagi- / plagio-", "Prefix: sned, snedställd. (prefix) Av grek. plagios = sned. Ex: plagiocefali = snedställd, asymmetrisk skalle."),
    P("plas- / plaso-", "Prefix: forma, bilda, utveckling. (prefix) Av grek. plassein = forma. Ex: hyperplasi = ökat antal celler."),
    P("plasm- / plasmo-", "Prefix: plasma-, formbar grundsubstans. (prefix) Av grek. plasma = något format. Ex: cytoplasma = cellens grundsubstans."),
    P("plat- / platy-", "Prefix: bred, platt, flat. (prefix) Av grek. platys = bred, platt. Ex: platybasi = avplattad skallbas."),
    P("pleur- / pleuro-", "Prefix: lungsäck-; sida, revben. (prefix) Av grek. pleura = sida, revben. Ex: pleurit = lungsäcksinflammation."),
    P("plex- / plexo-", "Prefix: fläta, nervfläta; slag. (prefix) Av lat. plexus = fläta. Ex: plexus = nät av nerver eller kärl."),
    P("plica- / plicat-", "Prefix: veck-, vikning. (prefix) Av lat. plica = veck. Ex: plika = slemhinneveck."),
    P("pluri-", "Prefix: flera, mång-. (prefix) Av lat. plures = flera. Ex: pluripotent = som kan ge upphov till flera celltyper."),
    P("pne- / pneo-", "Prefix: andning-. (prefix) Av grek. pnein = andas. Ex: apné = andningsuppehåll; dyspné = andnöd."),
    P("pneum- / pneuma- / pneumat- / pneumato- / pneumon- / pneumono- / pneumo-", "Prefix: luft, gas; lunga; andning. (prefix) Av grek. pneuma = luft, andedräkt; pneumon = lunga. Ex: pneumoni = lunginflammation; pneumothorax = luft i lungsäcken."),
    P("pod- / podo-", "Prefix: fot-. (prefix) Av grek. pous (podos) = fot. Ex: podocyt = fotcell i njurnystanet."),
    P("poikil- / poikilo-", "Prefix: brokig, oregelbunden, växlande. (prefix) Av grek. poikilos = brokig. Ex: poikilocytos = olikformade röda blodkroppar."),
    P("poli- / polio-", "Prefix: grå; grå hjärnsubstans. (prefix) Av grek. polios = grå. Ex: poliomyelit = inflammation i ryggmärgens grå substans."),
    P("poly-", "Prefix: många, mycket, flerfaldig. (prefix) Av grek. polys = mycket. Ex: polyuri = stora urinmängder."),
    P("por- / poro-", "Prefix: por, öppning, gång; förhårdnad. (prefix) Av grek. poros = passage, por. Ex: porös = full av smågångar."),
    P("porphyr- / porphyro-", "Prefix: purpur-, rödviolett. (prefix) Av grek. porphyra = purpur. Ex: porfyri = ämnesomsättningssjukdom med rödfärgad urin."),
    P("post-", "Prefix: efter, bakom. (prefix) Av lat. post = efter. Ex: postoperativ = efter operation."),
    P("postero-", "Prefix: bakre, baktill. (prefix) Av lat. posterior = bakre. Ex: posterolateral = baktill och åt sidan."),
    P("pre- / prae-", "Prefix: före, framför. (prefix) Av lat. prae = före. Ex: prenatal = före födelsen."),
    P("presby-", "Prefix: ålders-, åldrande. (prefix) Av grek. presbys = gammal. Ex: presbyopi = ålderssynthet."),
    P("prim- / primi-", "Prefix: först, främst. (prefix) Av lat. primus = först. Ex: primipara = förstföderska."),
    P("pro-", "Prefix: före, framför; för, i stället för. (prefix) Av grek./lat. pro = före, framför. Ex: prognos = förhandsbedömning."),
    P("proct- / procto-", "Prefix: ändtarm-, anus. (prefix) Av grek. proktos = ändtarm. Ex: proktit = ändtarmsinflammation."),
    P("pros- / proso-", "Prefix: mot, framåt, framtill. (prefix) Av grek. pros = mot, vid. Ex: prosencefalon = framhjärnan."),
    P("prostat- / prostato-", "Prefix: prostata-, blåshalskörtel. (prefix) Av grek. prostates = framförstående. Ex: prostatit = prostatainflammation."),
    P("proter- / protero-", "Prefix: tidigare, föregående. (prefix) Av grek. proteros = tidigare. Ex: protero- = föregående (sällsynt)."),
    P("prot- / proto-", "Prefix: först, ursprunglig, primär. (prefix) Av grek. protos = först. Ex: protoplasma = cellens urämne."),
    P("proxim- / proximo-", "Prefix: närmast (bålen), närliggande. (prefix) Av lat. proximus = närmast. Ex: proximal = närmare kroppens centrum."),
    P("pseud- / pseudo-", "Prefix: falsk, sken-, oäkta. (prefix) Av grek. pseudes = falsk. Ex: pseudoartros = falsk led (felläkt benbrott)."),
    P("psor- / psoro-", "Prefix: klåda, skorv. (prefix) Av grek. psora = klåda. Ex: psoriasis = fjällande hudsjukdom."),
    P("psych- / psycho-", "Prefix: själ, sinne, psyke. (prefix) Av grek. psyche = själ. Ex: psykologi = läran om själslivet."),
    P("psychr- / psychro-", "Prefix: köld-, kall. (prefix) Av grek. psychros = kall. Ex: psykrofil = köldälskande organism."),
    P("pteryg- / pterygo-", "Prefix: vinge-, vingformig; vingben. (prefix) Av grek. pteryx (pterygos) = vinge. Ex: processus pterygoideus = vingutskottet."),
    P("ptyl- / ptyalo-", "Prefix: saliv-. (prefix) Av grek. ptyalon = saliv. Ex: ptyalism = ökad salivutsöndring."),
    P("pub- / pubi- / pubo-", "Prefix: blygdben-, könshår. (prefix) Av lat. pubes = könshår, blygd. Ex: symphysis pubis = blygdbensfogen."),
    P("pulmo- / pulmon- / pulmono-", "Prefix: lunga-. (prefix) Av lat. pulmo (pulmonis) = lunga. Ex: pulmonell = som rör lungorna."),
    P("pupill- / pupillo-", "Prefix: pupill-. (prefix) Av lat. pupilla = pupill (egentl. liten docka). Ex: pupillometri = mätning av pupillvidd."),
    P("py- / pyo-", "Prefix: var-, varbildning. (prefix) Av grek. pyon = var. Ex: pyuri = var i urinen."),
    P("pycl- / pyclo-", "Prefix: tät, tjock, kompakt. (prefix) Av grek. pyknos = tät. Ex: pyknos = förtätning/skrumpning av cellkärnan. [källflagga: trol. = pykn-/pykno-]"),
    P("pyel- / pyelo-", "Prefix: njurbäcken-. (prefix) Av grek. pyelos = tråg, bäcken. Ex: pyelit = njurbäckeninflammation."),
    P("pyle- / pylephleb- / pylephlebo-", "Prefix: portåder-. (prefix) Av grek. pyle = port. Ex: pylephlebit = inflammation i portådern."),
    P("pylor- / pyloro-", "Prefix: portvakt-, magmun. (prefix) Av grek. pyloros = portvakt. Ex: pylorus = magsäckens nedre öppning."),
    P("pyr- / pyret- / pyreto- / pyro-", "Prefix: eld, värme, feber. (prefix) Av grek. pyr = eld; pyretos = feber. Ex: pyrexi = feber; antipyretika = febernedsättande."),
    # --- Q ---
    P("quadr- / quadri-", "Prefix: fyra, fyrfaldig. (prefix) Av lat. quattuor = fyra. Ex: quadriceps = fyrhövdad lårmuskel."),
    P("quinti-", "Prefix: femte, fem. (prefix) Av lat. quintus = femte. Ex: quintipara = kvinna som fött fem barn."),
    # --- R ---
    P("radic- / radicu- / radiculo-", "Prefix: rot-, nervrot. (prefix) Av lat. radix (radicis) = rot. Ex: radikulit = inflammation i en nervrot."),
    P("radi- / radio-", "Prefix: 1) strålning, röntgen; 2) strålben (radius). (prefix) Av lat. radius = stråle, eker. Ex: radiologi = läran om medicinsk bilddiagnostik."),
    P("re-", "Prefix: åter, igen, tillbaka. (prefix) Av lat. re = åter. Ex: reposition = återförande till rätt läge."),
    P("rect- / recto-", "Prefix: ändtarm-, rak. (prefix) Av lat. rectus = rak (rectum = ändtarmen). Ex: rektal = som rör ändtarmen."),
    P("ren- / reni- / reno-", "Prefix: njure-. (prefix) Av lat. ren = njure. Ex: renal = som rör njuren."),
    P("retro-", "Prefix: bakåt, bakom, tillbaka. (prefix) Av lat. retro = bakåt. Ex: retroperitoneal = bakom bukhinnan."),
    P("rhabd- / rhabdo-", "Prefix: stav-, tvärstrimmig. (prefix) Av grek. rhabdos = stav. Ex: rabdomyolys = sönderfall av tvärstrimmig muskulatur."),
    P("rhe- / rheo-", "Prefix: flöde, ström. (prefix) Av grek. rhein = flyta. Ex: reologi = läran om materials flytegenskaper (t.ex. blod)."),
    P("rhin- / rhino-", "Prefix: näsa-. (prefix) Av grek. rhis (rhinos) = näsa. Ex: rinit = nässlemhinneinflammation."),
    P("rhiz- / rhizo-", "Prefix: rot-, nervrot. (prefix) Av grek. rhiza = rot. Ex: rizotomi = avskärning av nervrot."),
    P("rhod- / rhodo-", "Prefix: röd, rosenröd. (prefix) Av grek. rhodon = ros. Ex: rodopsin = synpurpur i näthinnan."),
    P("rose- / roseo-", "Prefix: rosa, skär. (prefix) Av lat. roseus = rosenröd. Ex: roseol = rosafärgade hudfläckar."),
    P("rostr- / rostro-", "Prefix: näbb-, framåt mot näbben. (prefix) Av lat. rostrum = näbb. Ex: rostral = mot näbb-/näsänden av hjärnan."),
    P("rubr- / rubro-", "Prefix: röd-; röda kärnan. (prefix) Av lat. ruber = röd. Ex: nucleus ruber = röda kärnan i mitthjärnan."),
]

PREFIXES += [
    # --- S ---
    P("sacchar- / saccharo-", "Prefix: socker-. (prefix) Av grek. sakcharon = socker. Ex: sackarid = kolhydrat."),
    P("sacr- / sacro-", "Prefix: korsben-. (prefix) Av lat. os sacrum = heliga benet (korsbenet). Ex: sakral = som rör korsbenet."),
    P("salping- / salpingo-", "Prefix: trumpet-; äggledare; örontrumpet. (prefix) Av grek. salpinx (salpingos) = trumpet. Ex: salpingit = äggledarinflammation."),
    P("sanguini- / sanguino-", "Prefix: blod-. (prefix) Av lat. sanguis (sanguinis) = blod. Ex: sangvinisk = blodfull, livlig."),
    P("sapr- / sapro-", "Prefix: rutten, förruttnelse. (prefix) Av grek. sapros = rutten. Ex: saprofyt = organism som lever på dött organiskt material."),
    P("sarc- / sarco-", "Prefix: kött-, muskelvävnad. (prefix) Av grek. sarx (sarkos) = kött. Ex: sarkom = elakartad tumör i stödje-/muskelvävnad."),
    P("scapho-", "Prefix: båt-, båtformig. (prefix) Av grek. skaphe = båt. Ex: os scaphoideum = båtbenet i handen."),
    P("scapul- / scapulo-", "Prefix: skulderblad-. (prefix) Av lat. scapula = skulderblad. Ex: skapulär = som rör skulderbladet."),
    P("scat- / scato-", "Prefix: avföring-, träck. (prefix) Av grek. skor (skatos) = träck. Ex: skatologi = upptagenhet vid avföring."),
    P("schist- / schisto-", "Prefix: kluven, spaltad. (prefix) Av grek. schistos = kluven. Ex: schistocyt = fragmenterad röd blodkropp."),
    P("schiz- / schizo-", "Prefix: klyva, kluven, splittrad. (prefix) Av grek. schizein = klyva. Ex: schizofreni = kluvet sinne."),
    P("scintill- / scintillo-", "Prefix: gnistra, scintillation. (prefix) Av lat. scintilla = gnista. Ex: scintigrafi = avbildning med radioaktiv strålning."),
    P("scirrh- / scirrho-", "Prefix: hård, hårdtumör. (prefix) Av grek. skirros = hård. Ex: skirr = hård, bindvävsrik cancerform."),
    P("scler- / sclero-", "Prefix: hård, förhårdnad; senhinna. (prefix) Av grek. skleros = hård. Ex: skleros = förhårdnad av vävnad."),
    P("scoli- / scolio-", "Prefix: krokig, sned. (prefix) Av grek. skolios = krokig. Ex: skolios = sidokrökning av ryggraden."),
    P("scot- / scoto-", "Prefix: mörker-. (prefix) Av grek. skotos = mörker. Ex: skotom = blind fläck i synfältet."),
    P("seb- / sebo-", "Prefix: talg-. (prefix) Av lat. sebum = talg. Ex: seborré = ökad talgproduktion."),
    P("secundi-", "Prefix: andra, sekundär. (prefix) Av lat. secundus = andra. Ex: secundipara = kvinna som fött två barn."),
    P("semi-", "Prefix: halv-. (prefix) Av lat. semi = halv. Ex: semilunär = halvmånformig."),
    P("sepsi- / sept- / septic- / septico- / septo-", "Prefix: 1) röta, infektion; 2) skiljevägg (septum). (prefix) Av grek. sepsis = förruttnelse; lat. septum = skiljevägg. Ex: sepsis = blodförgiftning; septum = skiljevägg."),
    P("ser- / sero-", "Prefix: serum-, vätske-. (prefix) Av lat. serum = vassla, vätska. Ex: serös = vätskeavsöndrande."),
    P("sesqui-", "Prefix: en och en halv. (prefix) Av lat. sesqui = en och en halv. Ex: sesquioxid = oxid med förhållandet 2:3."),
    P("sial- / sialo-", "Prefix: saliv-, spott. (prefix) Av grek. sialon = saliv. Ex: sialadenit = spottkörtelinflammation."),
    P("sider- / sidero-", "Prefix: järn-. (prefix) Av grek. sideros = järn. Ex: sideropeni = järnbrist."),
    P("sigmoid- / sigmoido-", "Prefix: S-formig; sigmoideum. (prefix) Av grek. sigma = bokstaven S. Ex: colon sigmoideum = den S-formade tjocktarmsdelen."),
    P("silic- / silico-", "Prefix: kisel-, kiseldioxid. (prefix) Av lat. silex (silicis) = flinta. Ex: silikos = stendammlunga."),
    P("sinistr- / sinistro-", "Prefix: vänster, åt vänster. (prefix) Av lat. sinister = vänster. Ex: sinistrokardi = hjärtat förlagt åt vänster."),
    P("sinu- / sinuo-", "Prefix: håla, bihåla, sinus. (prefix) Av lat. sinus = böjning, håla. Ex: sinuit = bihåleinflammation."),
    P("sit- / sito-", "Prefix: föda, näring. (prefix) Av grek. sitos = säd, föda. Ex: sitofobi = rädsla för att äta."),
    P("skelet- / skeleto-", "Prefix: skelett-, benstomme. (prefix) Av grek. skeletos = uttorkad kropp. Ex: skeletal = som rör skelettet."),
    P("somat- / somato-", "Prefix: kropp-, kroppslig. (prefix) Av grek. soma (somatos) = kropp. Ex: somatisk = som rör kroppen."),
    P("somn- / somni-", "Prefix: sömn-. (prefix) Av lat. somnus = sömn. Ex: insomni = sömnlöshet."),
    P("son- / sono-", "Prefix: ljud-. (prefix) Av lat. sonus = ljud. Ex: sonografi = ultraljudsundersökning."),
    P("spano-", "Prefix: knapp, sparsam, sällsynt. (prefix) Av grek. spanos = knapp. Ex: spanomenorré = sällsynta menstruationer."),
    P("sperm- / spermat- / spermato- / spermo-", "Prefix: sädescell-, sperma. (prefix) Av grek. sperma (spermatos) = säd. Ex: spermatogenes = bildning av spermier."),
    P("sphen- / spheno-", "Prefix: kil-, kilben. (prefix) Av grek. sphen = kil. Ex: os sphenoidale = kilbenet."),
    P("spher- / sphero-", "Prefix: klot-, klotformig. (prefix) Av grek. sphaira = klot. Ex: sferocyt = klotformig röd blodkropp."),
    P("sphygm- / sphygmo-", "Prefix: puls-. (prefix) Av grek. sphygmos = puls. Ex: sfygmomanometer = blodtrycksmätare."),
    P("spin- / spino-", "Prefix: ryggrad-, tagg, utskott. (prefix) Av lat. spina = tagg, ryggrad. Ex: spinal = som rör ryggmärgen/ryggraden."),
    P("spir- / spiro-", "Prefix: 1) andning (lat.); 2) spiral, vriden (grek.). (prefix) Av lat. spirare = andas; grek. speira = spiral. Ex: spirometri = mätning av lungvolymer; spiroket = spiralformig bakterie."),
    P("splanch- / splanchn- / splanchno-", "Prefix: inälv-, bukorgan. (prefix) Av grek. splanchnon = inälva. Ex: splanknisk = som rör inälvorna."),
    P("splen- / spleno-", "Prefix: mjälte-. (prefix) Av grek. splen = mjälte. Ex: splenomegali = förstorad mjälte."),
    P("spondyl- / spondylo-", "Prefix: kota-, ryggkota. (prefix) Av grek. spondylos = kota. Ex: spondylit = kotinflammation."),
    P("spongi- / spongio-", "Prefix: svamp-, svampig. (prefix) Av grek. spongia = tvättsvamp. Ex: spongiös = svampliknande (om benvävnad)."),
    P("spor- / sporo-", "Prefix: spor-, frö. (prefix) Av grek. spora = frö. Ex: sporozoit = infektiöst stadium hos malariaparasit."),
    P("squam- / squamo-", "Prefix: fjäll-, skiv-. (prefix) Av lat. squama = fjäll. Ex: skvamös = skivepitelartad."),
    P("staphyl- / staphylo-", "Prefix: druvklase-; gomspene. (prefix) Av grek. staphyle = druvklase. Ex: stafylokock = klasformig bakterie."),
    P("steat- / steato-", "Prefix: fett-, talg. (prefix) Av grek. stear (steatos) = fett. Ex: steatos = fettinlagring (t.ex. fettlever)."),
    P("sten- / steno-", "Prefix: trång, förträngning. (prefix) Av grek. stenos = trång. Ex: stenos = förträngning av ett kärl eller organ."),
    P("sterco-", "Prefix: avföring-, träck. (prefix) Av lat. stercus = träck. Ex: sterkobilin = brunt färgämne i avföringen."),
    P("stere- / stereo-", "Prefix: fast, rumslig, tredimensionell. (prefix) Av grek. stereos = fast. Ex: stereognosi = förmåga att känna igen föremål med känseln."),
    P("stern- / sterno-", "Prefix: bröstben-. (prefix) Av grek. sternon = bröst. Ex: sternal = som rör bröstbenet."),
    P("steth- / stetho-", "Prefix: bröstkorg-. (prefix) Av grek. stethos = bröst. Ex: stetoskop = lyssnarrör för bröstet."),
    P("stomat- / stomato-", "Prefix: mun-, mynning. (prefix) Av grek. stoma (stomatos) = mun. Ex: stomatit = munslemhinneinflammation."),
    P("strept- / strepto-", "Prefix: vriden, kedjeformig. (prefix) Av grek. streptos = vriden. Ex: streptokock = kedjeformig bakterie."),
    P("sub-", "Prefix: under, nedanför; nästan. (prefix) Av lat. sub = under. Assimileras till suc-, suf-, sug-, sum-, sup-, sur-, sus- före vissa konsonanter. Ex: subkutan = under huden."),
    P("super-", "Prefix: över, ovanför; för mycket. (prefix) Av lat. super = över. Ex: superficiell = ytlig."),
    P("supra-", "Prefix: ovanför, över. (prefix) Av lat. supra = ovanför. Ex: supraklavikulär = ovanför nyckelbenet."),
    P("syring- / syringo-", "Prefix: rör-, kanal; spruta. (prefix) Av grek. syrinx (syringos) = rör. Ex: syringomyeli = vätskefylld kanal i ryggmärgen."),
    P("syn-", "Prefix: med, samman, tillsammans. (prefix) Av grek. syn = med. Före b, m, p blir formen sym-. Ex: symfys = bengördelfog; syndrom = grupp av samtidiga symtom."),
    # --- T ---
    P("tachy-", "Prefix: snabb, hastig. (prefix) Av grek. tachys = snabb. Ex: takykardi = snabb hjärtrytm."),
    P("tal- / talo-", "Prefix: språngben-, fotled. (prefix) Av lat. talus = språngben. Ex: talus = fotledens språngben."),
    P("tarso-", "Prefix: fotrot-; ögonlocksbrosk. (prefix) Av grek. tarsos = fotsula, flätverk. Ex: tarsalben = fotrotens ben."),
    P("tauto-", "Prefix: samma, identisk. (prefix) Av grek. tauto = detsamma. Ex: tautomer = molekyl som finns i jämviktsformer."),
    P("techn- / techno-", "Prefix: konst, teknik, färdighet. (prefix) Av grek. techne = konst, hantverk. Ex: teknik = tillämpad färdighet."),
    P("tel- / tele- / telo-", "Prefix: fjärran, avstånd; ände, slut. (prefix) Av grek. tele = fjärran; telos = slut. Ex: telemedicin = vård på distans; telomer = kromosomens ände."),
    P("tempor- / temporo-", "Prefix: tinning-; tid. (prefix) Av lat. tempus (temporis) = tinning, tid. Ex: temporal = som rör tinningen."),
    P("ten- / tendin- / tendino- / teno-", "Prefix: sena-. (prefix) Av lat. tendo = sena (grek. tenon). Ex: tendinit = seninflammation."),
    P("ter- / teri-", "Prefix: tre gånger, trefaldig. (prefix) Av lat. ter = tre gånger. Ex: tertiär = av tredje ordningen."),
    P("terat- / terato-", "Prefix: missbildning-, monster. (prefix) Av grek. teras (teratos) = missfoster. Ex: teratogen = fosterskadande."),
    P("test- / testi-", "Prefix: testikel-. (prefix) Av lat. testis = testikel. Ex: testikulär = som rör testikeln."),
    P("tetra-", "Prefix: fyra. (prefix) Av grek. tettares = fyra. Ex: tetrapares = svaghet i alla fyra extremiteterna."),
    P("thalam- / thalamo-", "Prefix: synhög-, thalamus. (prefix) Av grek. thalamos = kammare. Ex: talamisk = som rör synhögen i mellanhjärnan."),
    P("thanat- / thanato-", "Prefix: död-. (prefix) Av grek. thanatos = död. Ex: eutanasi = barmhärtighetsdöd."),
    P("thec- / theco-", "Prefix: hölje, skida, fack. (prefix) Av grek. theke = behållare, skida. Ex: intratekal = inuti durasäcken kring ryggmärgen."),
    P("thelo-", "Prefix: bröstvårta-. (prefix) Av grek. thele = bröstvårta. Ex: telit = inflammation i bröstvårtan."),
    P("therap- / therapo-", "Prefix: behandling-, vård. (prefix) Av grek. therapeia = vård. Ex: terapi = behandling."),
    P("therm- / thermo-", "Prefix: värme-, temperatur. (prefix) Av grek. therme = värme. Ex: hypotermi = sänkt kroppstemperatur."),
    P("thorac- / thoraco-", "Prefix: bröstkorg-. (prefix) Av grek. thorax (thorakos) = bröstkorg. Ex: torakal = som rör bröstkorgen."),
    P("thromb- / thrombo-", "Prefix: blodpropp-, koagel. (prefix) Av grek. thrombos = klump, propp. Ex: trombos = blodproppsbildning."),
    P("thym- / thymo-", "Prefix: 1) bräss (thymus); 2) sinne, känsloläge. (prefix) Av grek. thymos = sinne, livskraft. Ex: tymus = brässen; dystymi = nedstämdhet."),
    P("thyr- / thyro- / thyroid- / thyroido-", "Prefix: sköldkörtel-; sköldformig. (prefix) Av grek. thyreos = sköld. Ex: tyreoidea = sköldkörteln."),
    P("tibi- / tibio-", "Prefix: skenben-. (prefix) Av lat. tibia = skenben, flöjt. Ex: tibial = som rör skenbenet."),
    P("toc- / toco-", "Prefix: förlossning, födelse. (prefix) Av grek. tokos = födelse. Ex: tokolys = hämning av värkar."),
    P("tom- / tomo-", "Prefix: snitt, skiva, skärning. (prefix) Av grek. tome = snitt. Ex: tomografi = skiktröntgen."),
    P("ton- / tono-", "Prefix: spänning, tonus, tryck. (prefix) Av grek. tonos = spänning. Ex: tonometri = mätning av ögats tryck."),
    P("top- / topo-", "Prefix: plats, läge. (prefix) Av grek. topos = plats. Ex: topisk = lokal, på ett bestämt ställe."),
    P("tox- / toxi- / toxico- / toxo-", "Prefix: gift-. (prefix) Av grek. toxikon = pilgift. Ex: toxisk = giftig; toxikologi = läran om gifter."),
    P("trache- / tracheo-", "Prefix: luftstrupe-. (prefix) Av grek. tracheia = luftstrupe (sträv). Ex: trakeotomi = öppning av luftstrupen."),
    P("trans-", "Prefix: genom, över, på andra sidan. (prefix) Av lat. trans = över. Ex: transdermal = genom huden."),
    P("traumat- / traumato-", "Prefix: skada-, sår. (prefix) Av grek. trauma (traumatos) = sår. Ex: traumatologi = läran om skador."),
    P("tri-", "Prefix: tre, trefaldig. (prefix) Av grek./lat. tri = tre. Ex: triceps = trehövdad muskel."),
    P("trich- / trichi- / tricho-", "Prefix: hår-. (prefix) Av grek. thrix (trichos) = hår. Ex: trikofagi = hårätande."),
    P("triquetr- / triquetro-", "Prefix: trekantig; tribenet. (prefix) Av lat. triquetrus = trekantig. Ex: os triquetrum = tribenet i handloven."),
    P("troph- / tropho-", "Prefix: näring, tillväxt. (prefix) Av grek. trophe = näring. Ex: hypertrofi = förstoring genom ökad cellstorlek."),
    P("tub- / tubo-", "Prefix: rör-, kanal; äggledare. (prefix) Av lat. tuba = rör, trumpet. Ex: tubar = som rör äggledaren."),
    P("tympan- / tympano-", "Prefix: trumhinna-, mellanöra. (prefix) Av grek. tympanon = trumma. Ex: tympanit = inflammation i mellanörat."),
    # --- U ---
    P("ul- / ulo-", "Prefix: 1) tandkött; 2) ärr. (prefix) Av grek. oulon = tandkött; oule = ärr. Ex: ulit = tandköttsinflammation."),
    P("ultr- / ultra-", "Prefix: bortom, utöver, över-. (prefix) Av lat. ultra = bortom. Ex: ultraljud = ljud över hörbart frekvensområde."),
    P("umbilic- / umbilico-", "Prefix: navel-. (prefix) Av lat. umbilicus = navel. Ex: umbilikal = som rör naveln."),
    P("ungui- / unguino-", "Prefix: nagel-, klo. (prefix) Av lat. unguis = nagel. Ex: ungual = som rör nageln."),
    P("uni-", "Prefix: en, enkel, ensidig. (prefix) Av lat. unus = en. Ex: unilateral = ensidig."),
    P("uran- / urano-", "Prefix: gom-; himmel. (prefix) Av grek. ouranos = gom, himmel. Ex: uranoplastik = gomplastik."),
    P("ureter- / uretero-", "Prefix: urinledare-. (prefix) Av grek. oureter = urinledare. Ex: ureterit = inflammation i urinledaren."),
    P("urethr- / urethro-", "Prefix: urinrör-. (prefix) Av grek. ourethra = urinrör. Ex: uretrit = urinrörsinflammation."),
    P("uri- / uric- / urico- / urin- / urino- / uro-", "Prefix: urin-; urinsyra. (prefix) Av grek. ouron = urin. Ex: urologi = läran om urinvägarna; urikemi = urinsyra i blodet."),
    P("uter- / utero-", "Prefix: livmoder-. (prefix) Av lat. uterus = livmoder. Ex: uterin = som rör livmodern."),
    P("uve- / uveo-", "Prefix: druvhinna-, uvea. (prefix) Av lat. uva = vindruva. Ex: uveit = inflammation i ögats druvhinna."),
    # --- V ---
    P("vagin- / vagino-", "Prefix: slida-; skida. (prefix) Av lat. vagina = slida, skida. Ex: vaginit = slidkatarr."),
    P("valv- / valvulo-", "Prefix: klaff-, valvel. (prefix) Av lat. valva = dörrhalva, klaff. Ex: valvulit = hjärtklaffsinflammation."),
    P("varic- / varico-", "Prefix: åderbråck-, utvidgad ven. (prefix) Av lat. varix (varicis) = åderbråck. Ex: varikocele = åderbråck i pungen."),
    P("vas- / vaso-", "Prefix: kärl-; sädesledare. (prefix) Av lat. vas = kärl. Ex: vasokonstriktion = sammandragning av kärl."),
    P("vascul- / vasculo-", "Prefix: kärl-, blodkärl. (prefix) Av lat. vasculum = litet kärl. Ex: vaskulit = kärlinflammation."),
    P("ven- / vene- / veni- / veno-", "Prefix: ven-, blodåder. (prefix) Av lat. vena = ven. Ex: venös = som rör venerna."),
    P("ventr- / ventri- / ventro-", "Prefix: buk-, framsida; kammare. (prefix) Av lat. venter = buk; ventriculus = liten buk/kammare. Ex: ventral = mot buksidan."),
    P("vertebr- / vertebro-", "Prefix: kota-, ryggkota. (prefix) Av lat. vertebra = kota. Ex: vertebral = som rör kotorna."),
    P("vesic- / vesico-", "Prefix: blåsa-, urinblåsa. (prefix) Av lat. vesica = blåsa. Ex: vesikouretral = mellan urinblåsa och urinledare."),
    P("vesicul- / vesiculo-", "Prefix: blåsa-, liten blåsa; sädesblåsa. (prefix) Av lat. vesicula = liten blåsa. Ex: vesikulär = blåsformig."),
    P("vibri- / vibrio-", "Prefix: krökt stav (bakterie); vibration. (prefix) Av lat. vibrare = svänga. Ex: vibrio = kommaformad bakterie."),
    P("viscer- / viscero-", "Prefix: inälv-, inre organ. (prefix) Av lat. viscera = inälvor. Ex: visceral = som rör de inre organen."),
    P("vit- / vita- / viti-", "Prefix: liv; vitamin. (prefix) Av lat. vita = liv. Ex: vitamin = livsnödvändigt ämne."),
    P("vitre- / vitreo-", "Prefix: glas-, glaskropp. (prefix) Av lat. vitrum = glas. Ex: corpus vitreum = ögats glaskropp."),
    P("vulv- / vulvo-", "Prefix: blygd-, yttre kvinnliga könsdelar. (prefix) Av lat. vulva = blygd. Ex: vulvit = inflammation i de yttre könsdelarna."),
    # --- X ---
    P("xanth- / xantho-", "Prefix: gul-. (prefix) Av grek. xanthos = gul. Ex: xantom = gulaktig fettinlagring i huden."),
    P("xen- / xeno-", "Prefix: främmande, gäst. (prefix) Av grek. xenos = främling. Ex: xenotransplantat = transplantat från annan art."),
    P("xer- / xero-", "Prefix: torr-. (prefix) Av grek. xeros = torr. Ex: xerostomi = muntorrhet."),
    P("xiph- / xipho-", "Prefix: svärd-, svärdformig. (prefix) Av grek. xiphos = svärd. Ex: processus xiphoideus = svärdsutskottet på bröstbenet."),
    P("xyl- / xylo-", "Prefix: trä-, ved. (prefix) Av grek. xylon = trä. Ex: xylos = träsocker."),
    # --- Z ---
    P("zo- / zoo-", "Prefix: djur-, levande. (prefix) Av grek. zoon = djur. Ex: zoonos = sjukdom som smittar från djur till människa."),
    P("zyg- / zygo-", "Prefix: ok-, par, förening; okben. (prefix) Av grek. zygon = ok. Ex: zygot = befruktad äggcell (förening av två könsceller)."),
    P("zym- / zymo-", "Prefix: jäsning-, enzym. (prefix) Av grek. zyme = surdeg, jäsning. Ex: enzym = ämne som påskyndar kemiska reaktioner."),
]

# === SLUT PREFIX-DATA ===


def main():
    data = json.loads(DATA.read_text(encoding="utf-8"))
    before = len(data)

    # 1. Ta bort gamla prefix-poster som ska ersättas.
    data = [e for e in data if e["term"] not in REMOVE]
    removed = before - len(data)

    # 2. Kollidera inte: kolla att ingen ny term redan finns kvar.
    existing = {e["term"] for e in data}
    clash = [p["term"] for p in PREFIXES if p["term"] in existing]
    if clash:
        raise SystemExit(f"FEL: nya termer krockar med befintliga: {clash}")

    # 3. Infoga varje ny post in-place i rätt bokstavsgrupp.
    for new in sorted(PREFIXES, key=lambda p: p["term"].casefold()):
        L = new["term"][0].upper()
        k = new["term"].casefold()
        idx = None
        for i, e in enumerate(data):
            if e["term"][0].upper() == L and e["term"].casefold() > k:
                idx = i
                break
        if idx is None:
            same = [i for i, e in enumerate(data) if e["term"][0].upper() == L]
            idx = (max(same) + 1) if same else len(data)
        data.insert(idx, new)

    DATA.write_text(
        json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    print(f"Borttagna gamla prefix: {removed}")
    print(f"Nya prefix tillagda: {len(PREFIXES)}")
    print(f"Totalt poster: {before} -> {len(data)}")


if __name__ == "__main__":
    main()
